### ISSUE TITLE
Unable to read parameter from MTL file (Landsat 7)

### ISSUE THREAD

**Issue by fegyi001** [davidfrantz/force#10]
I have an issue when trying to do generate Level-2 for Landsat7 data.

Right after starting the process, I receive the following error: 

> error in fname. Unable to read parameter from MTL file!

I tried also in debug mode with force-l2ps which produced the following log:

```txt
check that all meta is initialized, stack as well?
there are still some things to do int meta. checking etc

Mission: 0
Start of RSR array: 14
DN: LE07_L1TP_189027_20190823_20190919_01_T1_B1.TIF
 LMAX/LMIN 293.70/-6.20, QMAX/QMIN 255.00/1.00, R*/R+ 0.00186/-0.01, K1/K2 -32767.00/-32767.00
DN: LE07_L1TP_189027_20190823_20190919_01_T1_B2.TIF
 LMAX/LMIN 300.90/-6.40, QMAX/QMIN 255.00/1.00, R*/R+ 0.00209/-0.01, K1/K2 -32767.00/-32767.00
DN: LE07_L1TP_189027_20190823_20190919_01_T1_B3.TIF
 LMAX/LMIN 234.40/-5.00, QMAX/QMIN 255.00/1.00, R*/R+ 0.00199/-0.01, K1/K2 -32767.00/-32767.00
DN: LE07_L1TP_189027_20190823_20190919_01_T1_B4.TIF
 LMAX/LMIN 241.10/-5.10, QMAX/QMIN 255.00/1.00, R*/R+ 0.00291/-0.02, K1/K2 -32767.00/-32767.00
DN: LE07_L1TP_189027_20190823_20190919_01_T1_B5.TIF
 LMAX/LMIN 47.57/-1.00, QMAX/QMIN 255.00/1.00, R*/R+ 0.00277/-0.02, K1/K2 -32767.00/-32767.00
DN: LE07_L1TP_189027_20190823_20190919_01_T1_B7.TIF
 LMAX/LMIN 16.54/-0.35, QMAX/QMIN 255.00/1.00, R*/R+ 0.00263/-0.02, K1/K2 -32767.00/-32767.00
DN: NULL
 LMAX/LMIN -32767.00/-32767.00, QMAX/QMIN -32767.00/-32767.00, R*/R+ -32767.00000/-32767.00, K1/K2 666.09/1282.71
dtype: 8
sat: 255
refsys   = 189027
tier: 1

stack info for FORCE Digital Number stack - DN_ - SID -1
open: 0, format 1
datatype 5 with 0 bytes
filename: ./tmp/DIGITAL-NUMBERS.tif
nx: 8171, ny: 7181, nc: 58675951, res: 30.000, nb: 7
width: 245130.0, height: 215430.0
chunking: nx: 0, ny: 0, nc: 0, width: 0.0, height: 0.0, #: 0
active chunk: -1, tile X0000_Y0000
ulx: 537585.000, uly: 5367015.000
proj: PROJCS["WGS 84 / UTM zone 33N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",15],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32633"]]
par: DIR_LEVEL2: ./level2, DIR_TEMP: ./tmp, DIR_LOG: ./log, FILE_QUEUE: ./poolfile.pool, DIR_WVPLUT: NULL, DIR_AOD: NULL, FILE_TILE: NULL, FILE_DEM: ./dem/dem.tif, DIR_MASTER: NULL, TILE_SIZE: 30000.000000, BLOCK_SIZE: 3000.000000, RESOLUTION_LANDSAT: 30.000000, RESOLUTION_SENTINEL2: 10.000000, DO_REPROJ: 0, DO_TILE: 1, ORIGIN_LAT: 48.514552, ORIGIN_LON: 15.400338, PROJECTION: GLANCE7, RESAMPLING: 2, RES_MERGE: 2, TIER: 1, DO_TOPO: 1, DO_ATMO: 1, DO_AOD: 1, DO_BRDF: 1, MULTI_SCATTERING: 1, ADJACENCY_EFFECT: 1, WATER_VAPOR: 1.000000, IMPULSE_NOISE: 1, BUFFER_NODATA: 0, DEM_NODATA: -32767, MASTER_NODATA: -32767, MAX_CLOUD_COVER_FRAME: 100.000000, MAX_CLOUD_COVER_TILE: 100.000000, CLOUD_THRESHOLD: 0.225000, SHADOW_THRESHOLD: 0.020000, NPROC: 32, NTHREAD: 2, PARALLEL_READS: 0, DELAY: 3, TIMEOUT_ZIP: 30, OUTPUT_FORMAT: 1, OUTPUT_DST: 0, OUTPUT_AOD: 0, OUTPUT_WVP: 0, OUTPUT_VZN: 0, OUTPUT_HOT: 0, OUTPUT_OVV: 1
++band # 0 - save 1, nodata: 0, scale: 1.000000
wvl: 0.478263, domain: BLUE, band name: BLUE, sensor ID: LND07
Date: 2019-08-23 (235/34/737170) 09:26:17-00Z
++band # 1 - save 1, nodata: 0, scale: 1.000000
wvl: 0.560585, domain: GREEN, band name: GREEN, sensor ID: LND07
Date: 2019-08-23 (235/34/737170) 09:26:17-00Z
++band # 2 - save 1, nodata: 0, scale: 1.000000
wvl: 0.660991, domain: RED, band name: RED, sensor ID: LND07
Date: 2019-08-23 (235/34/737170) 09:26:17-00Z
++band # 3 - save 1, nodata: 0, scale: 1.000000
wvl: 0.834120, domain: NIR, band name: NIR, sensor ID: LND07
Date: 2019-08-23 (235/34/737170) 09:26:17-00Z
++band # 4 - save 1, nodata: 0, scale: 1.000000
wvl: 1.649829, domain: SWIR1, band name: SWIR1, sensor ID: LND07
Date: 2019-08-23 (235/34/737170) 09:26:17-00Z
++band # 5 - save 1, nodata: 0, scale: 1.000000
wvl: 2.207666, domain: SWIR2, band name: SWIR2, sensor ID: LND07
Date: 2019-08-23 (235/34/737170) 09:26:17-00Z
++band # 6 - save 1, nodata: 0, scale: 1.000000
wvl: 11.000000, domain: TEMP, band name: TEMP, sensor ID: LND07
Date: 2019-08-23 (235/34/737170) 09:26:17-00Z

init and check for stack struct, too?
error in fname. Unable to read parameter from MTL file!
```

Here is everything that is needed to reproduce the error: https://my.pcloud.com/publink/show?code=kZx1E9kZfuI5HIpsiD8QibgybiqhmYhOcSv7

This is how I tried: 
```force-l2ps imagery/ parameters.prm```

What went wrong?

**Comment by fegyi001** [comment]
In the FAQ I found this:

> Following error appears (L2PS) in the logfile: Unable to open MTL file. Parsing metadata failed. FORCE can only handle Landsat data processed by the Level 1 Product Generation System (LPGS) of USGS, which comes with an MTL text file (contains the metadata). Data processed with the outdated National Land Archive Production System (NLAPS) are not supported. Sorry.

This will be the problem then.

**Comment by fegyi001** [comment]
Wait, I realized that I do have MTL file in the imagery folder. So I reopen the issue :(

**Comment by fegyi001** [comment]
Examining the MTL file: it was being processed by LPGS which should be fine for FORCE (according to the FAQ).

> PROCESSING_SOFTWARE_VERSION = "LPGS_13.1.0"

**Comment by davidfrantz** [comment]
.. yep, it's a bug. I still need to figure out how to solve it, and will fix it asap

**Comment by fegyi001** [comment]
> .. yep, it's a bug. I still need to figure out how to solve it, and will fix it asap

Ok, good to hear that you know about it.

**Comment by davidfrantz** [comment]
I've uploaded a bug fix. The filename of the temperature band for Landsat 7 wasn't correctly parsed. Thanks for bringing this to my attention!

**Comment by fegyi001** [comment]
I hereby confirm that this fix indeed solved the problem. Thanks David!

![image](https://user-images.githubusercontent.com/4125222/77144761-04178180-6a87-11ea-85fe-d9bbebf9c37c.png)

**Comment by davidfrantz** [comment]
Great :)

btw., you should create a mosaic before visualizing - this will look 
much better, see e.g. here: 
https://davidfrantz.github.io/tutorials/force-datacube/datacube/

Dr. David Frantz
Geomatics Lab | Geography Department | Humboldt-Universität zu Berlin
e-mail: david.frantz@geo.hu-berlin.de
phone: +49 (0) 30 2093 6883
mail: Unter den Linden 6 | 10099 Berlin | Germany

Am 20.03.2020 um 08:44 schrieb Gergely Padányi-Gulyás:

**Comment by fegyi001** [comment]
Thanks David! I know about mosaic creation and building pyramids (gdaladdo etc), this was just a quick look at the results, not optimized for visualization.

**Comment by fegyi001** [comment]
Since I think this is quite an imortant fix, do you plan to release v3.0.2? Maybe with the updated documentation?

**Comment by davidfrantz** [comment]
Yes, I already tagged it 3.1.0. But still need to update the 
documentation. I am thinking of removing the version from the 
documentation and from the README.md (and only refer to latest) because 
I already notice that I lose track of keeping everything in sync. In any 
case, the version history page will be updated soon!


Dr. David Frantz
Geomatics Lab | Geography Department | Humboldt-Universität zu Berlin
e-mail: david.frantz@geo.hu-berlin.de
phone: +49 (0) 30 2093 6883
mail: Unter den Linden 6 | 10099 Berlin | Germany

Am 20.03.2020 um 08:55 schrieb Gergely Padányi-Gulyás:

**Comment by fegyi001** [comment]
Oh, I didn't notice that. Awesome! I quickly created new Docker tags for version 3.1.0: https://hub.docker.com/repository/docker/fegyi001/force/tags?page=1
