### ISSUE TITLE
Incomplete feature output when sampling .tif-stack 

### ISSUE THREAD

**Issue by janoschhemmi** [davidfrantz/force#107]
**Describe the bug**
When using ++PARAM_SMP_START++ on stacked .tif ( INPUT_FEATURE ~> 500 Bands), an incomplete number of features is returned in output .csv. 

**Expected behavior**
A returned .csv with features of all bands would be expected. As a workaround, a break up of bands in <200 per  INPUT_FEATURE gives expected output.  
[smp_Landsat.zip](https://github.com/davidfrantz/force/files/6675940/smp_Landsat.zip)

**Comment by davidfrantz** [comment]
Hi @janoschhemmi ,
this seems to be due to a 1024 character limitation when parsing the parameter file.
I will try to lift this limitation. For now, the workaround certainly is a good one.
Cheers,
David

**Comment by davidfrantz** [comment]
Hi @janoschhemmi , 
late, but I have now fixed this with https://github.com/davidfrantz/force/commit/ecef61684e844f42899ef216e9990ea7e329bbc1 in the develop branch.
There still is a character limitation, but this was now increased from 1024 to 65536. This should give you ample room to add features :)
Cheers,
David
