### ISSUE TITLE
Tiny bug in force-parameter

### ISSUE THREAD

**Issue by PabRod** [davidfrantz/force#113]
## Bug

The command:

```sh
force-parameter data/param/ LEVEL2 0 
```
adds empty spaces at the end of the names of some fields. Particularly: DO_ADD, DIR_AOD, MAX_CLOUD_COVER_TILE, CLOUD_BUFFER, SNOW_BUFFER and CLOUD_THRESHOLD.

For instance, it writes:

```sh
DO_AOD  = TRUE # <- this
DO_AOD = TRUE  # <- instead of this
```

Most parsers will likely ignore this, and it didn't really cause me any serious problem. But it kept me puzzled for a while when trying to compare two different parameter files generated by different means 😅.

## Setup
- Force v. 3.6.5
- Running on Ubuntu 18.04.5 LTS
- on my own laptop
- where force was installed as usual

**Comment by davidfrantz** [comment]
Hi @PabRod 

this is not really a bug, and does not affect the functioning of FORCE.
The parameter file parser in FORCE disregards multiple spaces, so these can be used to align the parameters in a more readable way, e.g.:

```
CLOUD_BUFFER  = 300
SHADOW_BUFFER = 90
SNOW_BUFFER   = 30
```

Cheers,
David
