### ISSUE TITLE
spectral indices formulars

### ISSUE THREAD

**Issue by AndreasRabe** [davidfrantz/force#12]
Please provide the used formulars for the spectral indices: NDVI,EVI,NBR,ARVI,SAVI,SARVI,TC-BRIGHT,TC-GREEN,TC-WET,TC-DI,NDBI,NDWI,MNDWI,NDSI,SMA

Perhaps I missed them in the docs? 
https://force-eo.readthedocs.io/en/latest/components/higher-level/tsa/param.html#parameterization

**Comment by davidfrantz** [comment]
Dear Andreas,
the docs are not finished yet. But you are right, the  information is missing. I will see to it, but it will need some time.
Thanks,
David

**Comment by AndreasRabe** [comment]
Hi David, 
no problem, but can you give me the long names for: ARVI, SARVI, TC-DI, NDBI, NDWI, MNDWI, NDSI, SMA
Then I can google the formulars on my own.
Regards
Andreas

**Comment by davidfrantz** [comment]
Hi Andreas,
you can find the papers in:
src/cross-level/cite-cl.c
Cheers,
David

**Comment by AndreasRabe** [comment]
Not sure if this would be a one-to-one match-up between paper and code? When looking for example for SARVI, I find different formulars for different Landsats and Sentinel 2, and I am not sure if this is what you do in FORCE. Maybe I better wait for the docs.

**Comment by davidfrantz** [comment]
Not sure what you mean. The paper for SARVI in ``src/cross-level/cite-cl.c`` is from 1994. Not much Sentinel-2 data at that time ;)

**Comment by davidfrantz** [comment]
If you need the exact equations and coefficients, you can look up the code in ``src/higher-level/index-hl.c``, start with the ``tsa_spectral_index`` function,
In FORCE, there are no different equations/coefficients for different sensors. All the same.

**Comment by AndreasRabe** [comment]
Wasn't able to access the paper and I googled :-), found that https://www.indexdatabase.de/db/i-single.php?id=134

Also not sure what values to use for the L and y parameters in the SARVI formular.

I will look into the code, thanks!

**Comment by davidfrantz** [comment]
@jakimowb has started a table in the docs (develop branch):
https://github.com/davidfrantz/force/commit/86c90f27a67d635bc3d370649944434444053b59
This is not yet finished and needs some additional info + cross-check against the code before going to master.

**Comment by AndreasRabe** [comment]
Nice! 
Without me thinking to much about it: 
What is G, R, C1, C2, B, L in the EVI?

**Comment by AndreasRabe** [comment]
@jakimowb tell me when it is finished, I then adopt all the indices for FORCE4QGIS

**Comment by jakimowb** [comment]
As mentioned above, the FORCE index implemention can be found here (_this_ is the reference):
https://github.com/davidfrantz/force/blob/master/src/higher-level/index-hl.c

For EVI, SAVI and MSAVI you might also have a look to
https://www.usgs.gov/land-resources/nli/landsat/landsat-surface-reflectance-derived-spectral-indices

**Comment by AndreasRabe** [comment]
@jakimowb  I mean the table @davidfrantz mentioned, the one from the docs:  docs/source/components/higher-level/tsa/param.rst

After this table is completed, I will include all the indices into FORCE4QGIS.

**Comment by davidfrantz** [comment]
Hi @AndreasRabe @jakimowb 

I updated the table: https://github.com/davidfrantz/force/commit/2b4cf8f227fdfb278b46e5c6a5711089419f3c3e

Please note that the indices added by @jakimowb were partially different from the ones used in FORCE. please use the latest version of the table.

Cheers,
David

**Comment by jakimowb** [comment]
@AndreasRabe as mentioned before, the table is already completed
https://github.com/davidfrantz/force/blob/develop/docs/source/components/higher-level/tsa/param.rst

**Comment by AndreasRabe** [comment]
perfect, thanks both of you
