### ISSUE TITLE
SSL Error when trying to download data with force-level1-csd

### ISSUE THREAD

**Issue by bountrisv** [davidfrantz/force#126]
Hello,

the force-leve1-csd tool fails to download some requested data from a server due to the server not having valid SSL certificates.

```
[2021-10-08 12:13:59,233] {pod_launcher.py:136} INFO - ERROR 1: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
[2021-10-08 12:13:59,234] {pod_launcher.py:136} INFO - ERROR 1: Error returned by server : server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none (60)
[2021-10-08 12:13:59,235] {pod_launcher.py:136} INFO - FAILURE:
[2021-10-08 12:13:59,236] {pod_launcher.py:136} INFO - Unable to open datasource `WFS:http://ows.geo.hu-berlin.de/cgi-bin/qgis_mapserv.fcgi?MAP=/owsprojects/grids.qgs&SERVICE=WFS&REQUEST=GetCapabilities&typename=landsat&bbox=' with the following drivers.
[2021-10-08 12:13:59,236] {pod_launcher.py:136} INFO -   -> `PCIDSK'
.
.
.
```

Command that causes it (omitting daterange and path arguments as they seem to be irrelevant):
```
force-level1-csd -s LT04,LT05,LE07,S2A -d {daterange} -c 0,70 {image_metadata_folderpath} {image_folderpath} {queue_filepath} {aoi_filepath}
```

FORCE ver: 3.6.5

The server seems to be owned by Humbold University of Berlin. Who would be the right person to contact for SSL certificate renewal here?

Thanks!

**Comment by ernstste** [comment]
Just in case you need the data asap:
You can manually select which Landsat footprints you would like to include or define a bounding box to work around the issue.

**Comment by ernstste** [comment]
FORCE uses ogr2ogr.
I can't reproduce the error either. The WFS works without issues using FORCE and QGIS here.

**Comment by bountrisv** [comment]
I tried the force-level1-csd command on two different cluster setups to avoid any possible caching. One thing I forgot to note is that I am on FORCE version 3.6.5. Could this be the culprit here?

**Comment by bountrisv** [comment]
Yep:
```root@test-force:~# ERROR 1: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
ERROR 1: Error returned by server : server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none (60)
ERROR 1: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
ERROR 1: Error returned by server : server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none (60)
FAILURE:
Unable to open datasource `WFS:http://ows.geo.hu-berlin.de/cgi-bin/qgis_mapserv.fcgi?MAP=/owsprojects/grids.qgs' with the following drivers.
  -> PCIDSK
.
.
.
  -> AVCE00
  -> HTTP
root@test-force:~#

**Comment by ernstste** [comment]
So there is an issue with GDAL running from within a docker container. 
The issue does not occur when running GDAL directly from bash (tested on 2.2.3, 3.0.4, 3.1.4, 3.3.1 just now).

If v3.4 resolves the issue - great! But I share your concerns about updating GDAL before doing some testing or at least having a proper changelog. In the meantime, the issue here can be avoided with a simple workaround: use a tile list or bounding box instead of a vector file as AOI (or run force-level1-csd directly from the shell).

**Comment by ernstste** [comment]
Well, is it 'all of a sudden'? I haven't used force-level1-csd with a shapefile/geopackage AOI in a docker container so far.
Take my words with a grain of salt as I don't know how the certificates are handled, but from my understanding this is what happens:
The handshake between server and client requires the client to have the certificates available. The docker container is lacking the certificates (or they are installed in a different location?), so the server refuses to accept the connection. 

You said it was working fine with the latest GDAL version. Will be interesting to see the changelog.

**Comment by davidfrantz** [comment]
I have used it in Docker containers previously. Although, on second thought, I am not sure if this was with a vector geometry or with tile IDs...
But anyways, it works with the latest GDAL Docker without mounting... So this is likely more related to the Docker build than to GDAL itself... They changed some things in the past days regarding the [Docker build](https://github.com/OSGeo/gdal/tree/master/gdal/docker), but idk..

It is good though that we might have a solution here.

Can you confirm @bountrisv ?
@steiner-sve , as you are running on Windows (or is it the Subsystem for Linux?), it would also be good if you could confirm whether this (with some adjustments I assume) works for you, too?

Cheers,
David

**Comment by ernstste** [comment]
@davidfrantz When interpreting the error message I assume that this is about missing certificates rather than expired ones. I may be wrong though.

@bountrisv Mounting a folder that only contains the ca-certificates.crt worked in my case.
You said it worked fine before - are you 100% sure that you used a shapefile/geopackage as AOI back then rather than a bounding box or tile list?

**Comment by bountrisv** [comment]
Yes, I will. Thank you all!
