### ISSUE TITLE
force-level1-sentinel2 problems with folder access

### ISSUE THREAD

**Issue by thielfa** [davidfrantz/force#13]
I tried to download S2 data using **force-level1-sentinel2**, query seems to work fine, but then error below occurs. MGRS tile folders are created, but remain emtpy.

```
[thielf@node128 s2_mv]$ force-level1-sentinel2 /home/thielf/s2_mv/level1 /home/thielf/s2_mv/level1/mvlist.txt "10.5936728817/54.6850110112,10.5936728817/53.1103025704,14.4123810102/53.1103025704,14.4123810102/54.6850110112,10.5936728817/54.6850110112" 2019-08-01 2019-08-31 0 40
2020-03-24_19:12:26 - Found 96 S2A/B files.
2020-03-24_19:12:26 - Found 96 S2A/B files on this page.

/home/thielf/s2_mv/level1/T33UUU/S2B_MSIL1 100%[=============================================================================================>] 796.54M  11.8MB/s    in 56s
ls: cannot access '/home/thielf/s2_mv/level1/T33UUU/S2B_MSIL1C_20190830T102029*.SAFE': No such file or directory

/home/thielf/s2_mv/level1/T33UUV/S2B_MSIL1 100%[=============================================================================================>] 610.87M  12.1MB/s    in 57s
ls: cannot access '/home/thielf/s2_mv/level1/T33UUV/S2B_MSIL1C_20190830T102029*.SAFE': No such file or directory
```

**Comment by davidfrantz** [comment]
Hi Fabian,

unfortunately, I cannot reproduce your issue. It works like a charm on my end:

`force-level1-sentinel2 level1 level1/mvlist.txt "10.5936728817/54.6850110112,10.5936728817/53.1103025704,14.4123810102/53.1103025704,14.4123810102/54.6850110112,10.5936728817/54.6850110112" 2019-08-01 2019-08-05 0 40`

level1/T33UUV/S2B_MSIL 100%[=========================>] 309.04M  61.7MB/s    in 4.6s
level1/T32UPE/S2B_MSIL 100%[=========================>] 798.54M  73.0MB/s    in 9.4s
level1/T33UUA/S2B_MSIL 100%[=========================>] 431.23M  63.5MB/s    in 6.4s
level1/T32UQE/S2B_MSIL 100%[=========================>] 278.25M  86.6MB/s    in 3.3s
level1/T32UQD/S2B_MSIL 100%[=========================>]  82.64M  84.5MB/s    in 1.0s
level1/T32UPF/S2B_MSIL 100%[=========================>] 624.01M  86.5MB/s    in 7.4s
level1/T33UUU/S2B_MSIL 100%[=========================>]  65.87M  68.7MB/s    in 1.0s
level1/T32UNF/S2B_MSIL 100%[=========================>] 746.41M  90.6MB/s    in 8.0s
level1/T32UNE/S2B_MSIL 100%[=========================>] 819.27M  40.5MB/s    in 14s
level1/T33UVA/S2A_MSIL 100%[=========================>] 667.89M   104MB/s    in 6.5s

Do you have write access to the directories that were created? Would be strange if not, but probably there are some issues with permissions or umask settings..

Is `unzip` installed?

Cheers,
David

**Comment by thielfa** [comment]
Thanks David,
unzip was not installed. Installing it fixed the issue!
