### ISSUE TITLE
Restricting github-Workflows in forked repos which include pushing an image to DockerHub

### ISSUE THREAD

**Issue by Florian-Katerndahl** [davidfrantz/force#131]
Hey David,
the two new Workflows "docker-publish-debug.yml" and "docker-debug.yml" result in every forked version trying to upload FORCE to Dockerhub. I thought this isn't the desired action/what should happen and[ added two conditionals to the workflows](https://github.com/Florian-Katerndahl/force/commit/812c5f68dcbfed8a6f38ecf8edde096b7a3b34e5), so they only get executed in your repo.
An alternative would be to disable the workflows manually, should this be the desired approach to stop said workflows I will refrain from opening a pr.

Cheers,
Florian

**Comment by davidfrantz** [comment]
Ah, in your first message it says "docker-publish-debug.yml" and "docker-debug.yml". This confused me, I assume that the latter should be "docker-publish.yml", right?

Yes, for the Docker test, it makes sense that this runs for everybody. 
Under "Actions", there is another one ("Compile"), which is not existing anymore. 
This was deprecated and substituted with the Docker Test.

Feel free to PR. I like that addition!

**Comment by Florian-Katerndahl** [comment]
@davidfrantz This is included in #130
