### ISSUE TITLE
Empty output with FORCE 7.3.2 (force-l2ps)

### ISSUE THREAD

**Issue by vincentschut** [davidfrantz/force#137]
S2 scenes that process (force-l2ps) perfectly fine with FORCE 7.3.1 and below, give me a totally empty (full nodata) output with 7.3.2.

I'm currently testing this with this scene ID: S2B_MSIL1C_20200602T032539_N0209_R018_T47NQB_20200602T080419, but until now found it an issue with any scene I tried. Only FORCE version changed, parameter file, dem, etc. all remained the same. I'm attaching here the full debug output for both runs, plus the force-l2ps parameter file.

Luckily ESA postponed (again) the introduction of baseline 4 (to Januari 2022), so there's no rush here.
If there's anything I can do to help debugging this, please let me know.

[force_stdout_3.7.1.txt](https://github.com/davidfrantz/force/files/7442433/force_stdout_3.7.1.txt)
[force_stdout_3.7.2.txt](https://github.com/davidfrantz/force/files/7442434/force_stdout_3.7.2.txt)
[force.prm.txt](https://github.com/davidfrantz/force/files/7442442/force.prm.txt)

**Comment by vincentschut** [comment]
Thanks!

**Comment by davidfrantz** [comment]
This is now fixed with https://github.com/davidfrantz/force/releases/tag/v3.7.3-fix.
Backward compatibility should be given again.

Thanks again!
