### ISSUE TITLE
Cloud mask command tool

### ISSUE THREAD

**Issue by smile4lee** [davidfrantz/force#147]
Hi @davidfrantz, 

The Fmask with CDI looks very efficient and impressive for cloud and shadow detection. Do you have a command tool for the cloud detection module without the full installation of FORCE?

From the tutorial (https://force-eo.readthedocs.io/en/latest/howto/l2-ard.html#tut-ard), I noticed that many parameters are required to produce the level-2 products, which contains the cloud detection. For a given Sentinel-2 SAFE folder, how could run the cloud detection directly to produce the cloud mask and shadow layer?

Thanks!

Frantz, D., Haß, E., Uhl, A., Stoffels, J. and Hill, J., 2018. Improvement of the Fmask algorithm for Sentinel-2 images: Separating clouds from bright surfaces based on parallax effects. Remote sensing of environment, 215, pp.471-481.

**Comment by davidfrantz** [comment]
Hi @smile4lee,

the cloud detection is built into the Level 2 Processing System.
Currently, there is no standalone tool.

You can disable the atmospheric correction, though (``DO_ATMO = FALSE``). If you also disable the data cubing operations (``DO_REPROJ and DO_TILE = FALSE``), the program will essentially only do the cloud detection.

In addition, you can use FORCE with Docker, which eliminates the installation: https://force-eo.readthedocs.io/en/latest/setup/docker.html

Hope this helps,
David

**Comment by smile4lee** [comment]
> 

Hi @davidfrantz,

I will try with the settings. Thanks!
