### ISSUE TITLE
Error when S2 Level 2 processing - blank BOA

### ISSUE THREAD

**Issue by dryginmo** [davidfrantz/force#148]
I´m running Force V. 3.7.2 on Ubuntu 18.04 . When processing Sentinel 2 data to Level 2 (no matter if for a single image or an archive directory) it´s either a blank BOA or a BOA with negative values that won´t display in QGIS or nothing at all processed. In the log file I get no error message. Sometimes after around 15 minutes there are products written, sometimes not. I skipped the topo correction, used only cloud free data, I checked my depency program versions, tried to process with and without data cube and nothing seems to work. If the empty BOA is processed the I also have a "_hot.tif" as auxilliary file which looks normal to me. All other auxilliary tif files are also empty.
What more information could I provide you with to get deeper into this issue?

Best regards

**Comment by vincentschut** [comment]
Hi, upgrading FORCE to 3.7.3-fix or 3.7.4 should fix this. The version you're using contains a bug causing empty S2 outputs that was fixed in 3.7.3.

**Comment by dryginmo** [comment]
Thanks for your reply. In the tutorial I have only found ways to install specific versions. How do I upgrade Force?

**Comment by vincentschut** [comment]
You just install that specific version. Just like how you installed 3.7.2, but then use the download for 3.7.4.

**Comment by ernstste** [comment]
Try using Docker if you can. It makes switching between releases very easy.

**Comment by dryginmo** [comment]
I´d just like to confirm that updating to 3.7.4 solved the issue :)
