### ISSUE TITLE
ETA improvements

### ISSUE THREAD

**Issue by jakimowb** [davidfrantz/force#15]
Long-running force algorithms provide an estimated time of arrival (ETA), which helps very much to organize and schedule processing time with other users.

A typical force-level2 output, for example, is like:

> Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
> ETA: 106005s Left: 3582 AVG: 29.59s  local:25/3847/100%/29.6s

meaning the processing is expected to be done in 106005 seconds. It would be nice to see this ETA in date-time-stamp ISO format as well, e.g. '2020-04-04T13:06:25'

**Comment by davidfrantz** [comment]
Yes, this is inconvenient...

``GNU parallel`` is used for job scheduling. The ETA is directly coming from parallel when using ``parallel --eta ...``. Afaik, there is no option to control the formatting of this...

Sorry, there
