### ISSUE TITLE
Chlorophyll Index red-edge truncated 

### ISSUE THREAD

**Issue by d-pflugmacher** [davidfrantz/force#152]
The force-higher-level program produces unexpected outputs when computing the Chlorophyll Index red-edge (Clre) index. The Chlorophyll Index output contains only the following integer values: -30000, -20000, -10000, 0, 10000, 20000, 30000. The index typically results in decimal values approximately between -3 and 3, that when scaled by 10000 should contain more values. Looks like the index was integer truncated prior to scaling.
 
FORCE version 3.7.0
OS: Ubuntu 20.04.3 LTS

**Comment by davidfrantz** [comment]
Hi @d-pflugmacher,

yes, there was a problem with integer division. Can you please try the latest dev version to see whether this fixed things?

**Comment by d-pflugmacher** [comment]
The latest dev version solves the issue. Thank you for the fast response!
Thanks!

**Comment by davidfrantz** [comment]
You're welcome. This fix will eventually sip through to the main branch, too (will take some time though).
Cheers,
David
