### ISSUE TITLE
Level 3 TSS and TSI differ from equivalent Level 2 data

### ISSUE THREAD

**Issue by dryginmo** [davidfrantz/force#156]
Hey everyone,

I´m processing level 3 TSS and TSI based on Sentinel 2 Level 2 data. When comparing pixel values for those 3 data sets from either single bands or indices (tested on NDVI), there is a huge difference in pixel values for the same location and date. The graphs show this behavior as example on the NIR channel calculated on a large roof of an industrial building. I have a project partner who processed the same data. I compared this level 3 data with my level 2 data and didn´t end up with such differences. I compared our parameter files and they barely differ in level 2 and level 3 processing. My colleaque uses force v. 3.6.5, I´m using v. 3.7.5 . What am I doing wrong? Is there a software bug in the force version 3.7.5? I attached my parameter files for level 2 and level 3 processing. I´m glad for any suggestion solving this issue.

Thanks for your response!

![image](https://user-images.githubusercontent.com/59568663/150959703-2f3ee4f1-f884-4069-882a-ebf217d25bc1.png)
[l2ps.txt](https://github.com/davidfrantz/force/files/7939594/l2ps.txt)
[tsa.txt](https://github.com/davidfrantz/force/files/7939595/tsa.txt)

**Comment by davidfrantz** [comment]
Hi @dryginmo ,

can you provide a bit more information? Were the TSS data generated from the same Level 2 data that are shown in the image?

**Comment by dryginmo** [comment]
The TSS is indeed generated from the very same Level 2 data. It should thereby be equivalent to the TSS data, though this is not the case for my processing.

**Comment by ernstste** [comment]
Hi,

you say the parameter files that you and your colleague are using 'barely differ'. Maybe it would be good to start there: what is the actual difference?
From what I can see in your param file, you chose set `STANDARDIZE_TSI `and `STANDARDIZE_TSS `to `NORMALIZE`. It is to be expected that the values for your TSS are not the same as the L2 values after normalization.

**Comment by dryginmo** [comment]
Thank you so much for this hint! I just tested the standardization = NONE for TSS and TSI and now the pixel values stick together.
