### ISSUE TITLE
force-cube output name

### ISSUE THREAD

**Issue by jakimowb** [davidfrantz/force#16]
force-cube can be used to rasterize vector data into binary masks (https://davidfrantz.github.io/tutorials/force-masks/masks/). The written masks will have the same BASE_MASK name like the input vector file, just replacing the file extension with `*.tif`. E.g.

`force-cube vienna.shp /data/Dagobah/edc/misc/mask rasterize 10`
 
creates:
```
/data/Dagobah/edc/misc/mask/X0077_Y0058/vienna.tif
/data/Dagobah/edc/misc/mask/X0077_Y0059/vienna.tif
/data/Dagobah/edc/misc/mask/X0078_Y0058/vienna.tif
/data/Dagobah/edc/misc/mask/X0078_Y0059/vienna.tif
```
If would be nice if force-cube would have an optionally BASE_MASK argument, e.g.

`force-cube vienna.shp /data/Dagobah/edc/misc/mask rasterize 10 vienna10m.tif`

This would allow to :
* store different masks with different resolutions below the same mask directory
* to shorten or rename potentially long vector file names

**Comment by davidfrantz** [comment]
Good suggestion Benjamin,

I put this on my TODO list.

Just a quick note for the different resolutions: If you stay within FORCE, there is not much need to generate masks at different resolutions. If you generate them at sufficiently high resolution - let's say 10m - you can even input these masks if you are working on another analysis resolution, e.g. 30m, 50m, 100m, 1km etc.. (only drawback: the mask is read using Nearest Neighbor).

Cheers,
David

**Comment by davidfrantz** [comment]
@jakimowb ,

push https://github.com/davidfrantz/force/commit/fb2c0a9a6fd210b06b38452be084cb3d6b03e6d0 in the develop branch adds a new option `-b`, which allows you to define a custom basename for the output files.

Cheers,
David
