### ISSUE TITLE
Linear artifacts in Sentinel-2 LEVEL2 product(s)

### ISSUE THREAD

**Issue by thielfab** [davidfrantz/force#163]
I noticed a weird image artifact in a Sentinel-2 force-l2ps output. I compared the L2 image with the original L1 image, in the latter no artifact is to be seen. The pixel values in this bright stripe are all in the ~25000 range. Co-registration with Landsat base image was enabled (see parameterization below).
The Sentinel-2 image in this example is `S2B_MSIL1C_20210607T100559_N0300_R022_T....._20210607T142931.SAFE`. The tile is `X0069_Y0037` (@ernstste also found this artifact in their datacube)
Initially I thought it might be related to the MGRS tile and/or UTM zone overlap. But, a 2016-2021 Sentinel-2 NIR MAX time series across a larger part of the datacube reveals that the issue also occurs in other areas and within the tiles (not explicitly at MGRS overlaps, see image below). Maybe this has something to do with block level processing (the distance between parallel stripes is always ~5000m)? 
I did not yet check whether this also happens with co-registration disabled.

![grafik](https://user-images.githubusercontent.com/15610561/153404253-48bfa7e9-fdf6-4e98-b7f7-35d1b0d017c5.png)

![grafik](https://user-images.githubusercontent.com/15610561/153404364-6d7ce31d-b582-43c5-996c-96919fb5c1d8.png)

This image shows a vectorized version (for better viz) of a mask of 2016-2021_001-365_HL_TSA_SEN2L_NIR_STM_MAX where values > 10000 (no interpolation or filtering, default QAI options) 
![grafik](https://user-images.githubusercontent.com/15610561/153418687-997d92f4-12cc-4324-8f95-457aea78f709.png)

**Parameterization**
```
FORCE_param=DIR_LEVEL2: /home/userxy/edc/level2, DIR_TEMP: /home/userxy/temp, DIR_LOG: /home/userxy/edc/aux/logs, FILE_QUEUE: /home/userxy/edc/level1/sentinel2/queue_2021.txt, DIR_WVPLUT: NULL, DIR_AOD: NULL, FILE_TILE: NULL, FILE_DEM: /home/userxy/data/copernicus_dem/Europe/_VRT/Europe.vrt, DIR_COREG_BASE: /home/userxy/edc/base/mosaic, TILE_SIZE: 30000.000000, BLOCK_SIZE: 3000.000000, RESOLUTION_LANDSAT: 30.000000, RESOLUTION_SENTINEL2: 10.000000, DO_REPROJ: 1, DO_TILE: 1, ORIGIN_LAT: 60.000000, ORIGIN_LON: -25.000000, PROJECTION: PROJCS["ETRS89 / LAEA Europe",GEOGCS["ETRS89",DATUM["European_Terrestrial_Reference_System_1989",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6258"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4258"]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["latitude_of_center",52],PARAMETER["longitude_of_center",10],PARAMETER["false_easting",4321000],PARAMETER["false_northing",3210000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","3035"]], RESAMPLING: 2, RES_MERGE: 2, TIER: 1, DO_TOPO: 1, DO_ATMO: 1, DO_AOD: 1, DO_BRDF: 1, MULTI_SCATTERING: 1, ADJACENCY_EFFECT: 1, WATER_VAPOR: 0.000000, IMPULSE_NOISE: 1, BUFFER_NODATA: 0, DEM_NODATA: -32767, COREG_BASE_NODATA: -9999, ERASE_CLOUDS: 0, MAX_CLOUD_COVER_FRAME: 85.000000, MAX_CLOUD_COVER_TILE: 85.000000, CLOUD_BUFFER: 300.000000, SHADOW_BUFFER: 90.000000, SNOW_BUFFER: 30.000000, CLOUD_THRESHOLD: 0.225000, SHADOW_THRESHOLD: 0.020000, NPROC: 16, NTHREAD: 1, PARALLEL_READS: 0, DELAY: 8, TIMEOUT_ZIP: 30, OUTPUT_FORMAT: 1, OUTPUT_DST: 1, OUTPUT_AOD: 0, OUTPUT_WVP: 0, OUTPUT_VZN: 1, OUTPUT_HOT: 1, OUTPUT_OVV: 1
```

**Setup**
- FORCE version 3.7.5 (official force docker version)

**Comment by davidfrantz** [comment]
Just to let you know: I am still looking into this, but did not find out what is causing this, yet. I keep you posted

**Comment by davidfrantz** [comment]
@thielfab @ernsste do you know (or can check) if this happens since a specific date?

**Comment by geo-masc** [comment]
Did you already have a look at the QAI file? Not that this is a solution...but maybe a hint?
![QAI_S2B](https://user-images.githubusercontent.com/66110739/155702930-849668a6-6273-4a42-a36e-9aa40bd9e4d2.PNG)

**Comment by davidfrantz** [comment]
@geo-masc, yeah, with saturation filtering, you can at least get rid of most of these artefacts in the higher level processing. Though there are also some subzero artefacts..

**Comment by davidfrantz** [comment]
This is what I have found so far: there is something wrong at the edge of this one block.

In the background, you see the angles from the metadata (they come in 5km cells). I wonder whether this is related to a specific ESA processing baseline... 

![image](https://user-images.githubusercontent.com/32633788/155703575-76a34b64-5290-4128-8975-176d458a6185.png)

I will investigate further, but it would be nice to know since when this issue appears (or was it there all the time?).

**Comment by ernstste** [comment]
> I will investigate further, but it would be nice to know since when this issue appears (or was it there all the time?).

I'm pretty sure we talked about artefacts at S2 MGRS tile borders quite some time ago (2-3 years). Not sure if it was exactly the same problem, but those images remind me of it.

**Comment by davidfrantz** [comment]
I believe it was a different thing... I believe it was the rugged edge at the left side of the swath? Which was fixed, thus I am wondering whether there was a baseline change (we see a small edge missing here).

**Comment by davidfrantz** [comment]
I just found this gem in the code :D

``// try to fill the left edge (duplicate values - silly method, but it will do for now)``

The issue is likely related to the viewing grid in the metadata. I was never too happy with the implementation. But due to the overly complicated metadata, I went for a simplistic solution

**Comment by davidfrantz** [comment]
I might have a solution. I really hate these angle things... More next week

![image](https://user-images.githubusercontent.com/32633788/155742986-cc37f3d9-fab4-4e72-a06a-ac533b9c455d.png)

**Comment by thielfab** [comment]
Thanks David! 
Tested the new force version (on another studyarea/datacube), looks good 👍, stripes are gone.

**Comment by davidfrantz** [comment]
puh.. I am glad to hear this :)
