### ISSUE TITLE
Landsat 9

### ISSUE THREAD

**Issue by davidfrantz** [davidfrantz/force#165]
Landsat 9 data are now available from EarthExplorer, M2M etc.

@ernstste, could you please add the sensor to the csd script? :)

**Comment by ernstste** [comment]
I don't think they are available on GCS yet, but I can add L9 to ernstste/landsatlinks for now

**Comment by ernstste** [comment]
Actually - it already supports Landsat 9. Check your datacube, the files should already be in the queue if you use the same L1 download/processing procedures as you did in Berlin :)

**Comment by davidfrantz** [comment]
ah, yes, you are right...  

For ``force-level1-csd``, it does not make sense to add Landsat 9 since Google only stores Collection 1, because it has ceased forward processing in December 2021.

ernstste/landsatlinks works fine for the Collection 2 data :)

Sorry for this confusion
