### ISSUE TITLE
Force-higher-level doesn't catch keyboard interrupt

### ISSUE THREAD

**Issue by ernstste** [davidfrantz/force#172]
I am running some Python code using UDF in the higher level module and it doesn't seem like FORCE is able to catch keyboard interrupt signals (ctrl+c) to exit. 
Not sure whether this is specifically related to higher-level, but I remember it happened to me before (not sure which module, but definitely not using UDF). Only option to terminate seems to be sending term/kill signals through top/htop at the moment. This has not always been the case.

**Comment by davidfrantz** [comment]
Hi Stefan,

yes, killing with ``crtl+c`` worked in the past.
It stopped working when we started to link the C program against python to allow for the UDF stuff. 
I have no idea why this happens and unfortunately, I have no idea on how to fix this...

I am labeling this as ``help wanted`` in the slight hope that someone reading this might know what to do.
There is not much else I can do at the moment...

**Comment by Florian-Katerndahl** [comment]
Hey @ernstste & @davidfrantz,

I might have a solution for the bug (if I understood the problem correctly). While testing, I was able to terminate the UDF-process with `SIGINT`, i.e. `ctrl+c`.  I can't tell, whether this is indeed the correct way, so maybe take the solution with a grain of salt?!

Cheers,
Florian

![grafik](https://user-images.githubusercontent.com/29142246/159365080-4d1e9e2a-4dfd-497f-b3fb-35d97058fa8c.png)

**Comment by davidfrantz** [comment]
Hi all,

Florian solved this issue :)

Many Thanks, this is much appreciated!
David
