### ISSUE TITLE
force-lut-modis freezes on 504 response from daac query

### ISSUE THREAD

**Issue by vincentschut** [davidfrantz/force#180]
We routinely use force-lut-modis in our landsat preprocessing chain. Lately, we had an issue where force-lut-modis seemed to be frozen and kept running for hours on end (we found out when it was running for 17 hours already).

The command was:
`force-lut-modis -d20220314,20220314 -cfalse /tmp/scenes/LC81270592022073LGN00/wvp/wvp_20220314.coo /tmp/scenes/LC81270592022073LGN00/wvp /tmp/scenes/LC81270592022073LGN00/wvp /tmp/scenes/LC81270592022073LGN00/wvp`.

Looking at the files, we saw that there was a `MOD03_2022-03-14.txt` file, but the contents were this:

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Could it be that force-lut-modis does not correctly detect a 504 response from the query that creates this .txt file, and then falls into some endless loop?
(Of course this is hard to investigate further or reproduce, as it only happens when the server is out of order.)

FORCE version is 3.7.7, running in ubuntu based docker in gke (kubernetes in google cloud).

**Comment by Florian-Katerndahl** [comment]
Based on this (very crude) example, it **could** be sufficient to set the following `CURLOPT`:

```C
#include <stdio.h>
#include <curl/curl.h>

int main() {
    CURL *curl = curl_easy_init();
    if(curl) {
        CURLcode ret;
        curl_easy_setopt(curl, CURLOPT_URL, "https://example.com/non_exitstent_url");
        curl_easy_setopt(curl, CURLOPT_FAILONERROR, 1L); // NOTE this line!
        ret = curl_easy_perform(curl);
        if(ret == CURLE_HTTP_RETURNED_ERROR) {
            printf("Error noticed. CURL error %d\n", ret);
        } else {
            printf("Error not noticed\n");
        }
    }
    return 0;
 }
```
```bash
gcc curl_error.c -lcurl
./a.out
```
Resources:
- https://curl.se/libcurl/c/libcurl-errors.html#CURLEHTTPRETURNEDERROR
- https://curl.se/libcurl/c/CURLOPT_FAILONERROR.html

Ofc, I can't test this with FORCE and can't tell if there's any additional clean-up/work needed. It doesn't look like it, but again: not sure.

**Comment by davidfrantz** [comment]
Hi @vincentschut,

sorry for taking so long to look into this. I just merged the fixed proposed by @Florian-Katerndahl, which seems to solve the issue.

Cheers,
David
