### ISSUE TITLE
Transformation failed, Datacube failed - Sentinel Level 2 Processing

### ISSUE THREAD

**Issue by dryginmo** [davidfrantz/force#185]
I tried to re-run my Sentinel 2 level 2 processing, using the very same data and parameter file from my previous run a few months ago. Now I suddenly get the following error: "Transformation failed. Computing upper left in dst_srs failed. Starting Datacube failed. Starting Datacube(s) failed."
Is it due to a Force version update from 3.7.4 to 3.7.5? That´s the only thing which changed since my old Sentinel 2 level 2 processing.
The Landsat level 2 data is produced in the same process without trouble.

Thanks for your ideas on this problem.

**Comment by davidfrantz** [comment]
This? https://github.com/davidfrantz/force/discussions/146

**Comment by dryginmo** [comment]
I can confirm that #146 solved my problem. Since this is more of an "issue" related problem I would suggest moving #146 from "discussion" to "issue" to improve the solution finding for all users.

**Comment by davidfrantz** [comment]
Conda :)

As far as I know, I cannot move a discussion to issues (only open a new one). However, with this thread here, I guess that the Conda-Env issue is now also findable from the issue page ;)
