### ISSUE TITLE
L7 + L9 + S2 ARD on the same day --> no STM output

### ISSUE THREAD

**Issue by ernstste** [davidfrantz/force#186]
I am observing a specific constellation of Level-2 data and parameterization causing the processing of STMs to fail for some tiles (no output, processing finishes in seconds).

After spending quite some time looking for the issue and trying to narrow down the problem, it seems like this happens where there is a Landsat 9 and Sentinel-2 scene for the same day. 
Output will be generated if 
a) the noise filter is switched off
b) either Landsat 9 or Sentinel-2 is removed from the sensor allow list

Has this been observed before?

**Comment by davidfrantz** [comment]
Hi Stefan,

I am not sure if I can look into this quickly. It might take a bit to find some time.

This reminds me of this issue that is still open:

https://github.com/davidfrantz/force/issues/74

Problem there was >= 3 obs per day. Could it be, that there are even some remaining Landsat 7 images? 2 obs per day is a rather usual scenario, which never caused any problem, no?

**Comment by ernstste** [comment]
Hi David,

That seems to be the issue, thanks! I just removed Landsat 7 from the sensor list and got some output.
This puts us in a bit of an awkward situation, since the current constellation with Landsat 7, 9 and S2 will lead to three observations per day regularly. 
By the way I checkd #74 just now and it seems like Leon got an error on an earlier version. For me it just completes within a second without throwing any error or warning.

**Comment by davidfrantz** [comment]
yes, I agree, we need to find a fix for this. Soon-ish ;)

However, since L7 is de-orbiting, it might be a good idea to offline the pre-Dec 2021 L7 data from the cube for now (a temporary renaming would suffice). Afaik, there won't be any new L7 data from now on.

Leon's error message and your silent behavior might be due to using Docker? I noticed a while ago that some crash messages are not transmitted through Docker. If you enter the container, and run in there, you *might* see something... (emphasis on might) :)

**Comment by ernstste** [comment]
Simply removing Landsat 7 from the allowed sensors can be a temporary workaround. In the situation I have at hand here it's less than ideal though since we basically need any data we can get our hands on. A custom script finding three scenes/day and renaming the corresponding L7 data would probably be the way to go.

The float exception message is still displayed when running the image interactively, correct!

**Comment by davidfrantz** [comment]
Hi Stefan,

> since we basically need any data we can get our hands on.

I am not sure if this is the best decision. Landsat 7 science imaging stopped on April 5. Landsat 9 was placed in the same orbit, which was previously occupied by Landat 7. Therefore, we are only talking about winter images (for Europe).

In addition, up to the end, it seems that Landsat 7 was in the same horizontal orbit. Landsat 9 has much higher observation capabilities. Thus, if you have a Landsat 7 image, you probably always have a Landsat 9 image as well (with better radiometric quality and without stripes). 

In addition, Landsat 7 was gradually lowered and had increasingly unfavorable illumination conditions at the end. Please see below for the last image that probably captured you on your ride to the institute ;)

So unless you want to do some funky analyses with a delta time of 1 and a half hours (that's actually quite cool), I would probably simply remove the Landsat 7 images (I might do this here on my end as well). *I am not saying that the bug shouldn't be fixed though..*

Landsat 7:

Start Time | 2022:095:08:40:27.7425000
Stop Time | 2022:095:08:40:54.4965000

![image](https://user-images.githubusercontent.com/32633788/164193118-a526c055-de0e-42c0-a834-6bf00fa84082.png)

Landsat 9:

Start Time | 2022:095:10:02:13.7559390
Stop Time | 2022:095:10:02:45.5259060

![image](https://user-images.githubusercontent.com/32633788/164192923-c8500f11-2955-431b-a765-859d487f53eb.png)

Cheers,
David

**Comment by ernstste** [comment]
Hi David,

yep, it's exactly those winter images that we were looking for in this specific case :)
However, you're right that we usually have a L9 scene for 2022 where there is a L7 scene. I wasn't fully aware of that since the data came in with some delay. The issue I was facing only occured in a single footprint at first. Now, after several iterations of pulling data new data, it occurs in almost the whole study area.
We're going to remove the L7 data for now. On another note, I was made aware that the orbit drift of L7 makes scientic analysis somewhat dubious after 2020 (thanks Kasia): https://doi.org/10.1016/j.srs.2021.100026
Not so serious: we definitely need the noise filtering to be able to handle 3 scenes/day to make sure that bad L7 data is averaged with the scientifically sound values coming from S2 and L9 data 👍

**Comment by jakimowb** [comment]
> So unless you want to do some funky analyses with a delta time of 1 and a half hours (that's actually quite cool), I would probably simply remove the Landsat 7 images

This time delta can make a difference in cloud coverage. Having two or more observations from the same day may greatly reduce the number of observational gaps caused by clouds or cloud shadows.

**Comment by davidfrantz** [comment]
Yes, latency is very different for the two Landsats..

![image](https://user-images.githubusercontent.com/32633788/164198278-741a481d-d1ac-4f53-b2d9-c59a0a683274.png)

The orbit drift was known for quite some time, and a BRDF correction helps to some degree. But lately, de-orbiting was accelerated, I believe. At some point, USGS and LST discussed whether they wanted to restore orbit (and probably kill L7 in the process) or continue drifting.

btw: orbit changes are not limited to Landsat 7: https://www.sciencedirect.com/science/article/pii/S003442571630325X

**Comment by davidfrantz** [comment]
> This time delta can make a difference in cloud coverage. Having two or more observations from the same day may greatly reduce the number of observational gaps caused by clouds or cloud shadows.

well, but observing at 8:40 or 10:00 in the winter makes a huge difference for cloud shadows... And even small objects on the ground cast a long shadow, too... I am just saying that it probably causes more problems than it does good

**Comment by davidfrantz** [comment]
@ernstste,

I just had a quick look at the code, and maybe, it was an easy fix. Can you please test the new dev branch?

**Comment by ernstste** [comment]
Looks good! I couldn't check in detail yet, but the output is generated without issues (apart from being caught off-guard by the new option required by the dev branch ;) )

Thanks David, that was really quick!
Will close this for now as it seems resolved.

**Comment by jakimowb** [comment]
Thanks, great work @davidfrantz !
