### ISSUE TITLE
Sentinel 2 Coregistration - Could not retrieve base image

### ISSUE THREAD

**Issue by dryginmo** [davidfrantz/force#190]
I´d like to process Sentinel 2 Level 2 data (from 2018 to 2021), coregistered on Landsat data as explained in the force coregistration tutorial. My Landsat data reaches one year further back than my Sentinel 2 data. I have folded the time series based on the month and sticked with my settings to the force tutorial. Though, when running the Sentinel 2 processing with coregistration I get the error: "Could not retrieve base image. First 5 digits = 'YYYY-'. Coregsitration failed."
The names of my base images yet start the following: "2017-2021_..."
Why is the base image not found?

Thanks for any suggestion.

**Comment by ernstste** [comment]
I'd guess that you provided a folder with datacube structure rather than a VRT/TIF file covering your area of interest. If that's not the case, some more info would be helpful to try and find the issue.

**Comment by davidfrantz** [comment]
Hi @dryginmo,

did you already try @ernstste's solution? This would be my guess as well.

Cheers,
David

**Comment by dryginmo** [comment]
Hi,

sorry for the late response. Your suggestion worked and I could produce coregistered Sentinel 2 data. The problem was that I forgot to create a mosaic for my data cube tiles and feed that to my parameter file.

Thanks again! Cheers :)
