### ISSUE TITLE
insert valid ranges into index table

### ISSUE THREAD

**Issue by AndreasRabe** [davidfrantz/force#22]
ARVI -10000 10000
BLUE 0 10000
EVI -10000 10000
GREEN 0 10000
MNDWI -10000 10000
NBR -10000 10000
NDBI -10000 10000
NDMI -10000 10000
NDSI -10000 10000
NDTI -10000 10000
NDVI -10000 10000
NDWI -10000 10000
NIR 0 10000
RED 0 10000
SARVI -10000 10000
SAVI -10000 10000
SWIR1 0 10000
SWIR2 0 10000
TCB 0 22893
**TCDI -3793 35433**
TCG -10804 7940
TCW -12915 7032

**Comment by AndreasRabe** [comment]
as discussed, we assume BOA between 0-10000 (i.e. 0-100%)

**Comment by davidfrantz** [comment]
Thanks Andreas,
seems like a clip is indeed needed for DI.
However, please compute again.. This can't be all correct, e.g. EVI can be > 10000.

**Comment by davidfrantz** [comment]
I will close this. After zooming, Andreas and I decided to not include valid ranges in the table. This is because computing theoretical limits (assuming reflectance 0-1) results in non-meaningful values that will never occur in reality.
