### ISSUE TITLE
force-parameter in TSA mode does not ouput HARMONIC_MODES, HARMONIC_FIT_RANGE, OUTPUT_NRT

### ISSUE THREAD

**Issue by maxfreu** [davidfrantz/force#220]
I just generated a template parameter file for time series analysis using `force-parameter tsa.prm TSA`. Then I edited the IO paths etc and ran `force-higher-lever tsa.prm`, resulting in following error on 3.7.8:

```
parameter HARMONIC_MODES was not set.
parameter HARMONIC_FIT_RANGE was not set.
parameter OUTPUT_NRT was not set.
Reading parameter file failed!
```

I would expect that these parameters are included and set to some default value.

**Comment by ernstste** [comment]
Seems like force-parameter is still missing those, see #219 and #203. Some info about the parameters can be found in the [changelog](https://force-eo.readthedocs.io/en/latest/history/v3/v378.html)

**Comment by davidfrantz** [comment]
Indeed, I forgot to implement this...

I will try to find some time this week to do so.

Best,
David

**Comment by davidfrantz** [comment]
Thanks Marcel, I pulled your changes into the dev branch! Much appreciated!
