### ISSUE TITLE
Potential race condition in force-cube

### ISSUE THREAD

**Issue by davidfrantz** [davidfrantz/force#226]
I just realized that commit https://github.com/davidfrantz/force/commit/152e9bd9651547682a263104e1d172f071705769 might have introduced a potential race condition when cubing multiple files in parallel.

This commit deletes empty directories in a loop. If *process B* happens to write an image between *process A*'s check for the directory being empty, and deleting it, we might lose some data.

There is only a little chance that this happens, but I guess this will need fixing.

**Comment by ernstste** [comment]
Good point. An alternative would be to search the datacube directory for empty folders after tiling has finished:
`find datacube_folder -type d -empty -exec rm -rf {} \;`

Question is: is that what the user expects? I don't see a reason why someone would want to preserve empty tile folders but who knows.

**Comment by davidfrantz** [comment]
yes, cleaning up afterward seems much more reasonable than trying to do this on the fly.

I guess, getting rid of the empty dirs is still a good idea.

**Comment by ernstste** [comment]
Fixed in #228 

I added a regex to only match tile directories, in case the user has other data stored in the same dir for some reason. Wouldn't be a happy surprise if some reference data or whatever goes missing without any trace ;)

**Comment by davidfrantz** [comment]
Very nice! Thanks Stefan :)
