### ISSUE TITLE
RTD is referencing an outdated revision

### ISSUE THREAD

**Issue by ernstste** [davidfrantz/force#244]
The readthedocs page for force-level1-landsat is referencing an outdated version of the documentation: https://github.com/davidfrantz/force/blob/2da8cb24bd14e38f6702ab8a40dd434b89994df1/docs/source/components/lower-level/level1/level1-landsat.rst
The current version of the main branch is: https://github.com/davidfrantz/force/blob/main/docs/source/components/lower-level/level1/level1-landsat.rst

I believe this is because RTD only pulls changes from the GH repo whenever there is a new release tag (i.e., my own fault for not being able to deliver the documentation earlier ;)? If feasible, it would probably a good idea to reference the commit that adds the updated documentation.

**Comment by davidfrantz** [comment]
hmm, the RTD is actually configured to display the dev branch... what is missing?

**Comment by ernstste** [comment]
In that case, the issue is that I pushed the update directly to the main branch
Do you want to just merge it or should I push again to the dev branch?

**Comment by davidfrantz** [comment]
Ah damn, I did not pay attention... my bad.

In general, the main branch should not be updated unless it is a release. But no biggie, it is only the docs. 

I just reverted the PR on main. Can you please push again to dev?

**Comment by ernstste** [comment]
Sorry, my bad. I never push code to the main branch, but I did think that was how we did it with the docs. Been a while.. ;)

Here is the new PR: #246

**Comment by davidfrantz** [comment]
:) Thanks!
