### ISSUE TITLE
Apparent data loss when selecting EQUI7-EU as output

### ISSUE THREAD

**Issue by SerRichard** [davidfrantz/force#256]
**Describe the bug**
Hello! Pretty sure this is a bug in FORCE, as my colleague and I have been able to replicate this anomaly across two FORCE deployments and with varying S2 file inputs. It appears that when defining the data-cube to re-project output to the equi7grid, we are consistently missing some outputs, see circled are of the image below. The S2 tile covers two other equi7 tiles which we would expect to see reflected in the product output.

S2 Grid as dashed line
Equi7Grid  as solid line

![cover_missing excalidraw](https://user-images.githubusercontent.com/63349506/203998236-60ef7fc0-6c69-4032-9005-7c13956867f6.png)

**Expected behavior**
We would expect 6 products to be output by FORCE, and not 4. This leads to orderly and repeated no data values across our ARD data. This doesn't seem to be down to the configuration of the prm file. If helpful, the input scene in this example is: S2B_MSIL1C_20200910T100559_N0209_R022_T32TPS_20200910T124936.

**Parameterization**
In case you suspect this could be on our side, here is an example of our current parameters, with only any file-path options blank. If you see anything spurious on our side please let me know and I can correct & rerun.

[example.prm](https://github.com/SerRichard/force-example/blob/main/example.prm)

**Setup**
- docker: davidfrantz/force:3.6.3
- cmd: force-l2ps (also produced with force-level2)
- I make no changes to the docker container.

Though my colleague is using a different setup, I am not 100% what it is. Tia for any feedback and time spent replying to this, if we can provide anything else just let me know.

**Comment by davidfrantz** [comment]
Hi @SerRichard,

I am not convinced yet that it is a bug. Have you tested with ``MAX_CLOUD_COVER_TILE  = 100``?

Cheers,
David

PS: you are using a nearly two year old release that should actually not work with newer S2 data anymore

**Comment by SerRichard** [comment]
Thanks for the speedy reply! Will change the parameter and also bump to 3.7.10! Will reply with findings!

**Comment by SerRichard** [comment]
Wonderful, this looks complete now! Many thanks! Will try do do a better job reading the parameterisation docs next time :wink:  !

**Comment by davidfrantz** [comment]
I am glad it worked. Best, David
