### ISSUE TITLE
Nodata value of CSO products set to 1

### ISSUE THREAD

**Issue by ernstste** [davidfrantz/force#26]
The nodata value of CSO products is set to 1 in FORCE v3 (according to gdalinfo and QGIS).

Expected behavior would be a value outside the range that is to be expected as output, i.e. a negative number.

Force 3 running on Ubuntu Server 18.04.4 LTS

**Comment by ernstste** [comment]
Quick update: 
Could this be an issue related to the blocks outside of the AOI? Those are all assigned the value 1. Areas that are within the blocks that are processed but masked out carry the value -32767. See attached image - apologies for the terrible drawing :)
![grafik](https://user-images.githubusercontent.com/15325433/84028265-b2e5a280-a990-11ea-8316-490ba88d36d8.png)

**Comment by davidfrantz** [comment]
Hi stee,

yes, I guess the nodata is inherited from the input data (QAI) on construction of the internal image struct. 
I think I am actively writing -32767 if there is nodata, but
if a block is completely skipped, nothing is written in there, and when writing, GDAL fills with the nodata from the metadata. 
I will need to explicitly set nodata. Then, I guess the problem will be gone. Still, I didn't find time to do so yet.

Cheers,
David

**Comment by davidfrantz** [comment]
This is now fixed with https://github.com/davidfrantz/force/commit/a7d3de5c9075d45f2e2d24a6a20cd705e15a36e3 in the develop branch for the CSO submodule.

Please try again!
Cheers,
David

**Comment by ernstste** [comment]
I did a quick check just now and the results look good.

Thanks David!
