### ISSUE TITLE
Changes in the authorization process for Google Cloud may affect force-level1-csd soon

### ISSUE THREAD

**Issue by ernstste** [davidfrantz/force#265]
Google is deprecating the authentication workflow used by standalone tools such as gsutil, which is part of force-level1-csd. From what I understand, logging in with the current authentication method will not be possible from next month on.

Possible workarounds are [using service account authentication for gsutil standalone](https://cloud.google.com/storage/docs/gsutil/commands/config#configuring-service-account-credentials), [authenticating via HMAC](https://cloud.google.com/storage/docs/gsutil_install?hl=en#hmac), or [installing gsutil as a part of the Google Cloud CLI and using its authentication workflow](https://cloud.google.com/storage/docs/gsutil_install?hl=en#sdk-install). 

So far I wasn't able to look into the different options, but it would be preferable to keep using a gsutil standalone solution. I would be happy to hear feedback if anyone has tried the mentioned methods.

**Comment by davidfrantz** [comment]
Thanks for the heads-up!

Does this still generate the .boto?

**Comment by ernstste** [comment]
It does, but there is a slight change: The path to the keyfile is specified in the .boto config file, so the location must be mounted under the same path when running FORCE in docker.

**Comment by davidfrantz** [comment]
Stupid question: where do I find the dashboard?

**Comment by ernstste** [comment]
Sorry David, I didn't see your reply earlier.
You probably have found it by now, but just in case:
`https://console.cloud.google.com --> IAM & Admin (menu to the left visible after clicking the three bars left of theGoogle logo at the top left) --> Service Account`

Our daily downloads went through without issues yesterday and today, so I'm wondering how serious Google was about the announced deadline....

**Comment by erfea** [comment]
FYI, this morning I was not able to set up the connection using the old identification protocol: I got an `Access blocked: GSUtil's request is invalid`. Unless it is only me, Google has fully migrated to the identification protocol. 
Sadly, the service account does not work for me either throwing the following error: 

```
Your "OAuth 2.0 Service Account" credentials are invalid. For more help, see "gsutil help creds", or re-run the gsutil config command (see "gsutil help config").
Could not parse JSON keyfile "/home/[username]/.boto" as valid JSON
CommandException: 1 file/object could not be transferred.
```
Could it be due to the fact that my google account is secured with two steps identification (pw + token)? It seems I am the only one who struggles with getting data from the google bucket.

**Comment by erfea** [comment]
Since January I needed to reconfigure the connection each time i wanted to pull data. later it became very more annoying as pull tasks were interrupted. Since I switched to the new method it works flawlessly.
