### ISSUE TITLE
[FR] Allow to define class weights in force-train

### ISSUE THREAD

**Issue by jakimowb** [davidfrantz/force#28]
**Problem**

Classification reference data can be very imbalanced, e.g. contain many more samples for a class like "forest" compared to rare observations like "bavarian beer tent".
Calibrating a ML classification model on such imbalanced data usually tends to optimize the model on the more frequent classes.

To deal with this, OpenCV allows to define the following parameters:

[CvSVMParams::CvSVMParams](https://docs.opencv.org/2.4/modules/ml/doc/support_vector_machines.html?highlight=support%20vector#cvsvmparams)
> class_weights – Optional weights in the C_SVC problem , assigned to particular classes. They are multiplied by C so the parameter C of class #i becomes class\_weights_i * C. Thus these weights affect the misclassification penalty for different classes. The larger weight, the larger penalty on misclassification of data from the corresponding class.

[CvDTreeParams::CvDTreeParams]()
>priors – The array of a priori class probabilities, sorted by the class label value. The parameter can be used to tune the decision tree preferences toward a certain class. For example, if you want to detect some rare anomaly occurrence, the training base will likely contain much more normal cases than anomalies, so a very good classification performance will be achieved just by considering every case as normal. To avoid this, the priors can be specified, where the anomaly probability is artificially increased (up to 0.5 or even greater), so the weight of the misclassified anomalies becomes much bigger, and the tree is adjusted properly. You can also think about this parameter as weights of prediction categories which determine relative weights that you give to misclassification. That is, if the weight of the first category is 1 and the weight of the second category is 10, then each mistake in predicting the second category is equivalent to making 10 mistakes in predicting the first category.

**Feature Request**

Allow to define class weights in the `force-train parameter.prm` file. Optimally, it can be used in a 3-class example like:

- `ML_CLASSWEIGHTS = NULL`

- `ML_CLASSWEIGHTS = balanced` adjust weights inversely proportional to class frequencies in the as n_samples / (n_classes * n_class_samples)
 
- `ML_CLASSWEIGHTS = 0.2 0.6 0.2` explicit weights, put highest weight on 2nd class

- `ML_CLASSWEIGHTS = 10 20 10` explicit weights, translate into fractions by class_weight / (sum of class weights)

**Comment by davidfrantz** [comment]
Hi Benjamin,

looks like a reasonable addition.

In the new ``force-synthmix`` module, we are using ``EQUALIZED`` or ``PROPORTIONAL`` as keywords, thus I would favor this over ``NULL`` and ``balanced`` due to reasons of consistency. 

To clarify, if priors are not set (like now) or if ``EQUALIZED`` would be used, we would have ``ML_CLASSWEIGHTS = 0.33 0.33 0.33`` in your 3-class example, correct? (Assuming we allow a small delta for the user input).

I would however vote to not allow option 4. Almost certainly, some users will accidentally use this incorrectly, e.g. miss a decimal like: ``ML_CLASSWEIGHTS = 1.0 2.0 10``

Cheers,
David

**Comment by jakimowb** [comment]
`BALANCED`, `EQUALIZED` or `PROPORTIONAL` - I don't mind as long these terms are well explained in the docs. 

Just in case users want to prioritize a specific class - how could they do so if not by using explicit class weights?
 
*Accidental misuse* can happen in other places as well. In this specific case it might be generally good to printout the final `ML_CLASSWEIGHTS`. In case of `ML_CLASSWEIGHTS = 1.0 2.0 10` this might be something like `selected class weights: 0.07, 0.15, 0.76`, but I think these final weights are of interest in every case (explicit, equalized or proportional sampling).

**Comment by davidfrantz** [comment]
``prioritize a specific class``: Option 3 will be available for sure. Option 4 is very easily misused, I like to reduce such cases wherever possible. 

Printing won't necessarily help, not every one looks into the log files, just sayin' ;)

**Comment by davidfrantz** [comment]
All right, here we go: https://github.com/davidfrantz/force/commit/c78b85e45d05d4d6c0f6dc94ca3d0a1026e56cf7

There is now the possibility to define class weights for the RF and SVM classification methods in ``force-train`` via ``FEATURE_WEIGHTS``

See here: https://force-eo.readthedocs.io/en/latest/components/auxilliary/train.html (reminds me that some part of the docs are still missing..)

@jakimowb can you please test if this all works?

I have also used the opportunity to allow multiple columns in the response file. The column of interest can be chosen with ``RESPONSE_VARIABLE``.

Cheers,
David
