### ISSUE TITLE
[FR] force-train parameter file: FILE_FEATURES and FILE_RESPONSE CSV file handling

### ISSUE THREAD

**Issue by jakimowb** [davidfrantz/force#29]
**Problem**

The `force-train` parameter file specifies the CSV files paths to `FILE_FEATURES` and `FILE_RESPONSE` that contain the features and labels/responses required to train a machine learning model.

As described in the parameter file, `FILE_FEATURES` has to be a:

````
# File that is holding the features for training (and probably validation).
# The file needs to be a table with features in columns, and samples in rows.
# Column delimiter is whitespace. The same number of features must be given
# for each sample. Do not include a header. The samples need to match the
# response file.
# Type: full file path
````

(`FILE_RESPONSE` accordingly)

Overall, these are quite some strict restrictions to the CSV. CSV files without a header line are hard to understand, in particular with increasing number of features/columns. It requires to save the "header" information somewhere else to document which inputs have been used for the model training. 

It think it is also uncommon that features and responses need to be separated into two CSV files. This complicates maintaining the set of reference data, i.e. features and corresponding labels, e.g. in a table-sheet software like Excel / LibreOffice.

**Recommendations**
I recommend the following improvements:

1. Allow for header lines in  `FILE_FEATURES` and `FILE_RESPONSE`.
  * both files still need to have the same number of lines, i.e. if existent, a header line needs to exist in both files
  * a header line exists, if the first line in `FILE_FEATURES` starts with an alphabetic character, e.g. matches the regular expression `^\s*[A-Za-z]`

2. Allow features and responses to be defined in the same CSV
* this could be the case if `FILE_FEATURES` and `FILE_RESPONSE` are the same
* in this case, the 1st column should always contain the response

3. Allow to specify the CSV column delimiter
* introduce a parameter `CSV_DELIMITER` that can be used to specify CSV delimiter different to white-space

**Comment by davidfrantz** [comment]
Hi Benjamin,

nowhere it is written that input files are csv. I am using plain and simple ascii text files throughout FORCE with white-space as separator.

The separation into features and response is because you might want to train different responses using the same features (and then apply multiple models in force-higher-level to the same set of features). Or test different features on the same response. This gives you much less redundancy.

Thanks for the suggestion, I will consider to allow for some of this in the future, but will keep the behaviour for now.

Cheers,
David

**Comment by jakimowb** [comment]
Isn't a text file that (i) uses a character like white-space to separate values (= white space is the delimiter/separator) and (ii) the newline character to separate data records implicitly a [CSV file](https://en.wikipedia.org/wiki/Comma-separated_values)?

I see your argument that the separation of features and response values into different CSV files avoids redundancy (and this is noting I intended to change with my recommendations above).

But how do recommend to document which features have been used in these multiple csv files?

By now it is required to document this in an additional file. For example, if I train 2 models with different feature sets, I need to create the feature CSV files _and_ a `featurenames.txt` to documenten which features have been used in each of the CSV files:
```
file1.csv NDVI, NBR, SAVI
file2.csv EVI, NBR, TC-GREEN
```
If, for example, a visual inspection `file1.csv` reveals strange values, I first need to identify the column number, and then go into `featurenames.txt` to find out that these strange values relate to, e.g. the SAVI.

Allowing for header values instead gives would give me this direct information directly, without the need to create `featurenames.txt`.
