### ISSUE TITLE
level-1-landsat-download: Some links seem to be broken

### ISSUE THREAD

**Issue by MandLisa** [davidfrantz/force#290]
Hi all,
I just tried to download Landsat data via force-level1-landsat-download (since no Landsat data from 1997 are available via force-level1-csd). All attempts ended in the following error message: Some links seem to be broken, please check: [List with ALL Landsat links). However, the manual download of the data via the links works. Therefore, I do not think that there is a problem with the URLs. I have also heard from others that it does not work anymore. Strangely enough, this error didn't exist a fortnight ago. 

**Setup**
Always add information on your system, e.g.
- FORCE version 3.7.10
- OS and version: NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
- bare metal Linux server or virtual machine? VM
- did you deviate from the installation instruction? No
- CPUs: 2x Intel Xeon Gold 5220R CPU (24 cores each), RAM: 768 GB RAM

Thanks,
Lisa

**Comment by ernstste** [comment]
Hi Lisa,
I can't reproduce the issue. Could you share the full command you are using and post some of the links?

**Comment by ernstste** [comment]
Thanks Lisa,

the links look fine and they don't cause any issues when I use them with force-level1-landsat. 
I'm not really sure what to tell you. Feel free to post your `urls_landsat_TM_20230524T073439.txt` and I can try to see if anything pops up.

Thanks,
Stefan

**Comment by MandLisa** [comment]
Hi Stefan,
this is quite strange. I've just run level1-landsat-search again to create a new URL list, but I got the same error. This is the list I used: 

[urls_landsat_TM_20230524T073439.txt](https://github.com/davidfrantz/force/files/11561600/urls_landsat_TM_20230524T073439.txt)

Thanks for your help!

**Comment by ernstste** [comment]
Very strange indeed - this file works just fine here.
Are you able to work around the issue by using `force-level1-landsat search --download` to directly download the search results instead of creating the download link list first and then downloading by running `force-level1-landsat download`?

**Comment by MandLisa** [comment]
We now tried to run the download command on three different servers. Strangely enough, on one server `force-level1-landsat download` is working now. So I guess the issue is related to our servers (would explain why it is working for you). We will figure out what's going on here.

Thanks Stefan!

**Comment by davidfrantz** [comment]
Could this be related to some USGS-quotas?

**Comment by ernstste** [comment]
> Could this be related to some USGS-quotas?

Every link in the text file is checked against a regex, the error that Lisa describes is thrown if that check fails. 
So no - USGS has nothing to do with it, since this is just a local check to make sure we're that all files can be downloaded and we're not downloading arbitrary links.
