### ISSUE TITLE
[develop branch] CSO error "doube free or corruption (out)"

### ISSUE THREAD

**Issue by jakimowb** [davidfrantz/force#30]
**Bug Description**

I like to calculate the annual number of clear observations using `/develop/force-higher-level level2_cso.prm` (prm file attached).
Everything is fine when using a `MONTH_STEP` < 12. In case of `MONTH_STEP = 12` the COS calculation is aborted and it looks like that only some of the image lines are written:

(This affects the current develop version, not the last master)

````bash
/develop/force-higher-level /data/Jakku/diss_bj/level2_cso.prm
number of processing units: 50
 (active tiles: 1, chunks per tile: 50)
________________________________________
Progress:                          0.00%
Time for I/C/O:           100%/000%/000%
ETA:                   not available yet
________________________________________
                   input compute  output
Processing unit:       1       0      -1
Tile X-ID:            49      49      -1
Tile Y-ID:            27      27      -1
Chunk ID:              1       0      -1
Threads:               8      22       4
Time (sec):            2       0       0
double free or corruption (out)
[1]    33302 abort (core dumped)  /develop/force-higher-level /data/Jakku/diss_bj/level2_cso.prm
````

**Parameterization**

````
DATE_RANGE = 2015-01-01 2020-12-31
DOY_RANGE = 1 365
CSO = NUM
````

details see 
[level2_cso.zip](https://github.com/davidfrantz/force/files/4890123/level2_cso.zip)

**Setup**

"Ubuntu 18.04.4 LTS
BB8, 120 cores, RAM 754 GB

````bash
/develop/force-higher-level data/Jakku/diss_bj/level2_cso.prm
````

**Comment by davidfrantz** [comment]
additional info provided by @jakimowb via email:

gdb complains about line 192 in stack-cl.c:
  if (stack->nodata      != NULL) free((void*)stack->nodata);

**Comment by davidfrantz** [comment]
Hi Benjamin,

in response to issue https://github.com/davidfrantz/force/issues/26, I accidentally introduced a bug with commit https://github.com/davidfrantz/force/commit/a7d3de5c9075d45f2e2d24a6a20cd705e15a36e3 in the develop branch.

This is now fixed with commit https://github.com/davidfrantz/force/commit/0292273a05e16321b258f015fddfcd5a6669c74c.

Thanks,
David
