### ISSUE TITLE
Inconclusive error message resulting from typo in RFC param file

### ISSUE THREAD

**Issue by ernstste** [davidfrantz/force#31]
FORCE 3.2.1 higher-level (RFC classification) throws following error message if the file listed under FILE_MODEL does not exist:

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.0) /home/[I_removed_this_part]/src/opencv-4.1.0/modules/core/include/opencv2/core.hpp:3133: error: (-215:Assertion failed) fs.isOpened() in function 'load'

Aborted (core dumped)

```
This is rather cosmetics and I was lucky enough to catch my mistake within 2 minutes. I am surprised though. Does FORCE not check whether DIR_MODEL+FILE_MODEL exist? It does throw a specific error message if DIR_MODEL does not exist.

**Comment by davidfrantz** [comment]
Hmm yes, apparently not.. will fix asap

**Comment by davidfrantz** [comment]
Hi Stefan, 

this is now fixed with https://github.com/davidfrantz/force/commit/65911430f17be9ccbaed2849990e25927f0205f3 in the develop branch.

Cheers,
David

**Comment by ernstste** [comment]
Uhm...I guess you meant it when you said asap.
Thanks!
