### ISSUE TITLE
Sentinel-2 Volume 11 and Volume 12: FORCE differences from sen2cor

### ISSUE THREAD

**Issue by neteler** [davidfrantz/force#310]
We observe differences in band 11 and 12 of Sentinel-2 Level 2A tiles comparing those available on Google Earth Engine (GEE - "S2_SR" collection, which is the Copernicus Sentinel-2 Level 2A operational product processed with sen2cor https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR) and same S2 tiles processed by FORCE.
 
 In order to reproduce everything, we have downloaded scene S2A_MSIL1C_20180619T112111_N0206_R037_T29SPC and
 - processed it with sen2cor v2.10 (same as used for GEE data of this date)
 - processed it with FORCE v 3.7.10 (BRDF OFF)

In both cases we switched off the DEM usage in order to simplify reproducibility.

**Describe the bug**

The following plot shows the spectral signature averaged over the entire pixels of the processes scene. The difference in bands 11 and 12 is visible averaging over all pixels of a scene and thus seems to be systematic:

![image](https://github.com/davidfrantz/force/assets/1295172/f5bfaa4e-f8e4-4f9a-9150-f5a728fd9a79)

Looking at many test points across different scenes we observe most differences between band 11 and 12:

![image](https://github.com/davidfrantz/force/assets/1295172/89fe0298-3c0f-4d7c-8f74-72a9c12f62b7)

**Expected behavior**

We expect more similarity or hints why the differences occur or which atmospheric correction method is to be preferred.

We are aware of the paper "Atmospheric Correction Inter-comparison eXercise, ACIX-II Land: An assessment of atmospheric correction processors for Landsat 8 and Sentinel-2 over land" (https://doi.org/10.1016/j.rse.2022.113412) yet curious how to deal with these differences which quite influence e.g. the Normalised Burn Radio (NBR2).

**Parameterization**

The configuration files for both sen2cor and FORCE are attached.
[force_sen2cor_configs.zip](https://github.com/davidfrantz/force/files/12868465/force_sen2cor_configs.zip)

**Setup**

- FORCE v 3.7.10 (BRDF OFF)
- sen2cor v2.10 (same as used for GEE data of this date)
- Linux Ubuntu 22.04
- virtual machine
- no deviations from the installation instruction
- 25 GB RAM + 25 GB swap and 8-core CPU

**Comment by davidfrantz** [comment]
Hi @neteler,

this here is not an issue. The right place for this, would be the discussion forum.

Different atmospheric corrections are simply different and it is quite cumbersome to repeatably answer questions regarding the intercomparison to other ACs. For this, there have been the ACIX erxercises.

Important is, FORCE has been rigorously validated and intercompared. Please see that FORCE is very well within specification in all the SR-analyses in ACIX-II (see e.g. Fig 5). Please also note that Sen2Cor is missing for that analyses as their developers pulled out of that specific intercomparison as they did not like the results. 

From the RadCalNet site comparison (Fig 6  top), you see that FORCE's error in Band 11 is way below that of Sen2Cor.

That said, I don't know why the values are different, but naturally, I trust FORCE more..

**Comment by neteler** [comment]
Thanks @davidfrantz, for your comments. We were not fully aware that Sen2Cor chose to not publish that specific intercomparison. Closing this issue ("won't fix" is blocked for me, though).
