### ISSUE TITLE
Problem with GDAL >= 3.0

### ISSUE THREAD

**Issue by davidfrantz** [davidfrantz/force#32]
There currently is an incompatibility of FORCE with ``GDAL >= 3.0``.

Since ``GDAL >= 3.0``, the coordinates from coordinate transformation operations are no longer sorted as X/Y or LON/LAT, but in the typical order of each coordinate system ([Link](https://trac.osgeo.org/gdal/wiki/rfc73_proj6_wkt2_srsbarn#Axisorderissues)).

```C

  x = utm_x; // easting
  y = utm_y; // northing

  transf = OGRCreateCoordinateTransformation(&SRS_UTM, &SRS_WGS);

  transf->Transform(1, &x, &y);

````

In ``GDAL < 3.0``, this code snippet transforms x to longitude, and y to latitude.
Since ``GDAL 3.0``, this code snippet transforms x to latitude, and y to longitude.

**Until I have fixed this, it is not recommended to use FORCE with ``GDAL >= 3.0``!**

**Comment by vincentschut** [comment]
Hi David, would you have any timeline on this? Just informing, no pressure intended. We're eager to switch our entire processing pipeline to gdal3, and FORCE is probably the last thing that keeps us on gdal2.4...
Note that a workaround could be relatively simple: according to this paragraph https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order it should suffice to call `.SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);` on any OGRSpatialReference instance to restore the old behaviour.

**Comment by jakimowb** [comment]
@davidfrantz this relates to https://github.com/OSGeo/gdal/issues/1974 

> GDAL 3 honours now by default CRS axis order. Either use transform.TransformPoint(y, x) or set .SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER) on your source and/or dest objects. See https://github.com/OSGeo/gdal/blob/release/3.0/gdal/MIGRATION_GUIDE.TXT#L7

Obviously a very common problem, as it is already mentioned in the GDAL repositories issue template:

> If you think there is an issue with coordinate order in GDAL 3.0, then it is
likely an intended behaviour. See 
for more explanations.

**Comment by davidfrantz** [comment]
Hi Vincent and Benjamin,

I eventually had some time to look into this, to set up a test system, and to write a test program..

I am in good hope that this issue is now fixed with https://github.com/davidfrantz/force/commit/259d154801d80ad9cd72f385de3d64c33c8d83bd in the develop branch. I am planning to merge this branch to master in less than a week.

Adding this line to each coordinate transformer did the trick:
``CPLSetConfigOption("OGR_CT_FORCE_TRADITIONAL_GIS_ORDER", "YES"); ``

I think it is now safe to use FORCE with GDAL >= 3.0 :)

Cheers,
David

**Comment by vincentschut** [comment]
Thanks for the quick follow-up!
