### ISSUE TITLE
error in higher level TSA folding statistic

### ISSUE THREAD

**Issue by chrisraab** [davidfrantz/force#33]
Hi David,

I am deriving higher level, quarterly folded TSA results for different statistics using Landsat data. The region of interest is small and intersects with just four Landsat tiles.

For AVG, KRT, MAX, MIN, RNG, SKW and STD it is working. However, for IQR, Q25, Q50, Q75 it appears that I get a memory related error.

`force-higher-level LEVEL3_TSA... .prm` 

results in the following error message:

*** Error in `force-higher-level': free(): invalid next size (fast): 0x00007fc670184e30 ***
Abgebrochen (Speicherabzug geschrieben)

 
I am using FORCE 3.4.0 complied on Ubuntu 16.04 (virutal machine) with six cores and 16 GB RAM.

Christoph

**Comment by davidfrantz** [comment]
Dear Christoph,

thanks for reporting this bug. This is fixed now with https://github.com/davidfrantz/force/commit/980b4ec2646bb9ecb009b50032072b3965c445ef in the develop branch. The change will be included in the next master version, too, expected to be released in a week or so.

Cheers,
David
