### ISSUE TITLE
Feature request: force-level1-csd

### ISSUE THREAD

**Issue by jonasardo** [davidfrantz/force#39]
Hi

It would be useful if the optional arguments -n and -k could be combined so metadata could be extracted to file for data already on disk. This would be an easy way to find data with certain criteria. Currently I don't get any metadata (csd_metadata_YYYY-MM-DDTHH-MM-SS) when combining these or when searching for data downloaded before.

Regards
/Jonas

[jonasardo@aurora-nateko Uganda]$ force-suite force-level1-csd -d 20170101,20201008, -k  -s S2A,S2B  -c 0,0 /projects/eko/fs2/FORCE/metadata/ ./L1/ ./L1/TMP.txt T36NXG

Querying the metadata catalogue for Sentinel2 data
Sensor(s): S2A,S2B
Tile(s): T36NXG
Daterange: 20170101 to 20201008
Cloud cover minimum: 0%, maximum: 0%

18 Sentinel2 Level 1 scenes matching criteria found
3.51GB data volume found.

Starting to download 18 Sentinel2 Level 1 scenes

Scene S2A_MSIL1C_20200120T080241_N0208_R035_T36NXG_20200120T094031(18 of 18) exists, skipping...

|========================================================================================================================================================================================================================| 100 %
Done.

**Comment by ernstste** [comment]
Hi Jonas,

this should actually work fine, but I neglected updating the help when switching to version 3.5.2.
The output directory of the -k | --keep-meta option was changed from the metadata directory to the level-1 datapool. The reason behind the change is that in many use cases, the large metadata catalogues are likely to be used by several users, while the level 1 datapool is more likely to be project / user specific. We assume that it's not desirable that many users write their filtered metadata to the same shared folder (also, there's a possibility that writing rights area restricted) and therefore decided to use the level 1 datapool instead.

So unless something went wrong, you should be able to find the filtered metadata from your requests in the l1 pool folder. Please let me know if that is not the case.

Stefan
