### ISSUE TITLE
Vertical striping in landsat boa image after running force-l2ps

### ISSUE THREAD

**Issue by vincentschut** [davidfrantz/force#43]
**Describe the bug**
After running force-l2ps, vertical striping is apparent in the resulting boa image. The striping is not there in the original landsat band files, neither is it in the dem. So it is probably FORCE that is adding it. The striping gets stronger when the adjacency correction is enabled, but is also there without adjacency correction.

2 landsat scene id's where this is happening:
* LC81260582019090LGN00
* LE71260582019114EDC00

screenshot of LC81260582019090LGN00 (bands 5/4/3) boa image:
![LC81260582019090LGN00](https://user-images.githubusercontent.com/659645/96104022-a0e4b500-0ed8-11eb-9fbd-d38bf388be21.png)

**Expected behavior**
After running force-l2ps, I expect to get a boa image without vertical striping artifacts.

**Parameterization**
Command: `force-l2ps /dprof_data/tmp/scenes/LC81260582019090LGN00 /dprof_data/tmp/scenes/LC81260582019090LGN00/force.prm`
[force.prm](https://github.com/davidfrantz/force/files/5383689/force.prm.txt) (renamed to force.prm.txt otherwise github won't let me attach it)

**Setup**
- FORCE version: 3.5.2
- OS and version: Ubuntu 20.04.1 LTS
- GDAL version: 3.1.3
- running in docker (derived from osgeo/gdal:ubuntu-full-3.1.3)
- did you deviate from the installation instruction? -> no
- 64G, intel core i9 (8 cores, 16 hyperthreading threads)

**Comment by davidfrantz** [comment]
Hi Vincent,

thanks for reporting this, this looks strange indeed.

Do the quality flags indicate something? 

I don't think that FORCE adds something.. But I guess the atmospheric correction could be amplifying something..

The only "spatial" effect that FORCE might add would be much coarser, i.e. the sun and view angles are computed for 5km grid cells (your striping appears more small-scale), but then the retrieved atmospheric variables are interpolated...

I am trying to narrow this down a bit:

Is this especially pronounced in certain bands?

Have you tried outputting TOA images? ``DO_ATMO = FALSE``

Can you please check your DEM, and run a hillshade on the DEM? I know that SRTM has some vertical stripes once in a while..

Cheers,
David
