### ISSUE TITLE
Image not rendered in website

### ISSUE THREAD

**Issue by PabRod** [davidfrantz/force#46]
Hi.

I just want to report that, for some reason, the following image:

https://github.com/davidfrantz/force/blob/e49e8bd9070a5cee3ed742d44e89d13d9a06d516/docs/source/howto/sentinel2-l1c.rst#L25

doesn't get correctly rendered in [the website](https://force-eo.readthedocs.io/en/latest/howto/sentinel2-l1c.html#tut-s2l1c).

**Comment by ernstste** [comment]
Thanks for reporting, Pablo!
