### ISSUE TITLE
force-level1-csd on CIFS-mounted network drive

### ISSUE THREAD

**Issue by davidfrantz** [davidfrantz/force#49]
force-level1-csd throws an error and exits when working on a CIFS-mounted network drive:

```
force-level1-csd -s LT04,LT05,LE07 -c 0,70 download/metadata download/data download/queue.txt crete.shpSearching for footprints / tiles intersecting with geometries of AOI shapefile...
ERROR 1: sqlite3_exec(COMMIT) failed: database is locked
ERROR 1: sqlite3_exec(PRAGMA synchronous = OFF) failed: Safety level may not be changed inside a transaction
ERROR 1: sqlite3_exec(BEGIN) failed: cannot start a transaction within a transaction
ERROR 1: Transaction not established
ERROR 1: A file system object called 'merged.gpkg' already exists.
ERROR 1: GPKG driver failed to create merged.gpkg
```

Apparently, geopackage doesn't work on network drives in Unix....
https://gis.stackexchange.com/questions/327214/is-there-a-fix-for-sqlite3-execommit-failed-database-is-locked-qgis-3-6-pyt

When doing the same on a local directory or an ext4-mounted drive, it works without a problem.

**Comment by ernstste** [comment]
We will not use geopackages for the intersection of LS/S2 tiles and the AOI from the next release. Instead, a folder is created and the pre-selection of tiles + AOI are created there as shapefiles.
