### ISSUE TITLE
gdal-bin conflicting python-gdal with current releases on apt 

### ISSUE THREAD

**Issue by przell** [davidfrantz/force#51]
Dear David, 
I am currently installing the newest version of FORCE 3.5.2. And read that from 3.5.0 it supports gdal 3.

First I wanted to install it on a VM, which is the usage our researchers are used to. 
While installing the dependencies as stated in the docs there is an error:
```
sudo apt-get install libgdal-dev gdal-bin python-gdal
```
The error:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gdal-bin : Breaks: python-gdal (< 2.4.3~) but 2.2.3+dfsg-2 is to be installed
 python-gdal : Depends: gdal-abi-2-2-3
               Depends: libgdal20 (>= 2.2.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
You mention that you are testing with gdal 2.2.2 this is not available anymore currently on apt (just to let you know):
```
apt-cache policy gdal-bin
gdal-bin:
  Installed: (none)
  Candidate: 3.0.4+dfsg-1~bionic0
  Version table:
     3.0.4+dfsg-1~bionic0 500
        500 http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu bionic/main amd64 Packages
     2.2.3+dfsg-2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

 apt-cache policy libgdal-dev
libgdal-dev:
  Installed: (none)
  Candidate: 3.0.4+dfsg-1~bionic0
  Version table:
     3.0.4+dfsg-1~bionic0 500
        500 http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu bionic/main amd64 Packages
     2.2.3+dfsg-2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

 apt-cache policy python-gdal
python-gdal:
  Installed: (none)
  Candidate: 2.2.3+dfsg-2
  Version table:
     2.2.3+dfsg-2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

```

Then I tried the dockerized version as stated in the docks. It works. I have looked into the dockerimage and tried to replicate it on a plain ubuntu 18.04 VM. The same error occurs as stated above.
```
# Install libraries
RUN apt-get -y install wget unzip curl git build-essential libgdal-dev gdal-bin python-gdal \ 
  libarmadillo-dev libfltk1.3-dev libgsl0-dev lockfile-progs rename \
  parallel libfltk1.3-dev apt-utils cmake \
  libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev \
  python3.8 python3-pip
```

I wonder how or if this installation works in the docker?
I will go on with the installation now without python-gdal. Maybe it's not a hard dependency.
Best, 
Peter

**Comment by davidfrantz** [comment]
Hi Peter,
..ehm, I have no idea. This usually works fine for me, and since it works in the docker, too..
As far as I know, GDAL 3 is only available since Ubuntu 20, no?
Do you already have GDAL on this machine? Just a guess, as apt complains that you are holding broken packages..
Cheers,
David

**Comment by przell** [comment]
Hi David, 
thanks for the quick reply. 
It's indeed puzzling. There is no GDAL on the machine. It's ubuntu 18.04 and I ran apt-update before the installation of dependencies. 
However, the docker works like a charm. And I could convince my colleague to use it, by showing the ease of use and set up speed! Thanks for sharing the docker and the documentation!
All the best, 
Peter
P.S.: "Hi and thanks" from Ruth ;)

**Comment by przell** [comment]
Resolved by using the dockerized solution.
