### ISSUE TITLE
Possibility of using only the part "BRDF"

### ISSUE THREAD

**Issue by safalabolo** [davidfrantz/force#54]
Dear David,
I would need to apply reflectance normalization from Sentinel-2 (A/B) when acquisitions for the same granule are derived from different relative orbits.
Would there be the possibility of using only a part of the entire package (force)?
Thanks in advance for your reply

**Comment by davidfrantz** [comment]
Hi safalabolo,

I am afraid this is not possible out of the box. The BRDF correction is tied into the preprocessing.

You can certainly use the corresponding code snippets and compile your own executable, or translate to a different language.

Best regards,
David

**Comment by safalabolo** [comment]
Thank You David!
