### ISSUE TITLE
force-lut-modis crashing with gdal 3.2.0

### ISSUE THREAD

**Issue by vincentschut** [davidfrantz/force#56]
When force is compiled against gdal 3.2.0, force-lut-modis crashes. When force is compiled with gdal 3.1.3, it works ok.

For building force, we use the osgeo/gdal ubuntu-full-<version> docker images. When we build force in the osgeo/gdal ubuntu-full-3.2.0 image, force-lut-modis crashes:

create a dummy coordinate file:
```
echo "-92.3904 14.4691" > /wvp/wvp_20191017.coo
```
run force-lut-modis:
```
force-lut-modis /wvp/wvp_20191017.coo /wvp /wvp /wvp 2019 10 17 2019 10 17
```
output (in this case the modis data was already downloaded):
```
2019/10/17. do. TERRA geometa exists.
278 lines, 127 valid.
127 valid lines in geometa
AQUA geometa exists.
288 lines, 133 valid.
133 valid lines in geometa
requested box: UL -93.14/15.22, LR -91.64/13.72
1 intersecting granules
ERROR 4: : No such file or directory
ERROR 10: Pointer 'hDataset' is NULL in 'GDALGetRasterXSize'.

ERROR 10: Pointer 'hDataset' is NULL in 'GDALGetRasterYSize'.

ERROR 10: Pointer 'hDS' is NULL in 'GDALGetRasterBand'.

ERROR 10: Pointer 'hBand' is NULL in 'GDALRasterIO'.

could not read image. 100.0% of useful frames.
free(): invalid pointer
Aborted (core dumped)
```

**Expected behavior**
The hdf data can be read and converted, no errors happen, and no core dump.

**Setup**
FORCE version: tested with 3.5.2 and 3.6.1, both have the bug
ubuntu 20.04 (using these dockers: https://hub.docker.com/r/osgeo/gdal/tags?page=1&ordering=last_updated)

**Comment by davidfrantz** [comment]
Hi Vincent,

isnt't this rather a GDAL bug? It appears that the hdf file cannot be opened with this version..
Have you tried if the 3.2.0 commandline tools work with the hdf? (gdalinfo, gdal_translate etc.)

Cheers,
David

**Comment by vincentschut** [comment]
It might certainly be a gdal bug, but it's a bit more subtle than just that. It only happens (afaik) with the force-lut-modis tool, gdalinfo and gdal_translate can open and read the hdf file just fine. Running force-lut-modis with CPL_DEBUG=on suggests that the dataset gets closed immediately after opening:

```
force-lut-modis /dprof_data/tmp/scenes/LE70210502019290EDC00/wvp/wvp_20191017.coo /dprof_data/tmp/scenes/LE70210502019290EDC00/wvp /dprof_data/tmp/scenes/LE70210502019290EDC00/wvp /dprof_data/tmp/scenes/LE70210502019290EDC00/wvp 2019 10 17 2019 10 17
2019/10/17. do. TERRA geometa exists.
278 lines, 127 valid.
127 valid lines in geometa
AQUA geometa exists.
288 lines, 133 valid.
133 valid lines in geometa
requested box: UL -93.14/15.22, LR -91.64/13.72
1 intersecting granules
GDAL: GDALOpen(/dprof_data/tmp/scenes/LE70210502019290EDC00/wvp/MYD05_L2.A2019290.1950.061.2019295131917.hdf, this=0x55a33bea8730) succeeds as HDF4.
HDF4Image: List of dimensions in geolocation field "Latitude": Cell_Along_Swath_5km,Cell_Across_Swath_5km
HDF4Image: List of dimensions in geolocation field "Longitude": Cell_Along_Swath_5km,Cell_Across_Swath_5km
GDAL: GDALOpen(HDF4_EOS:EOS_SWATH:"/dprof_data/tmp/scenes/LE70210502019290EDC00/wvp/MYD05_L2.A2019290.1950.061.2019295131917.hdf":mod05:Water_Vapor_Near_Infrared, this=0x55a33c085330) succeeds as HDF4Image.
GDAL: GDAL_CACHEMAX = 3203 MB
GDAL: GDALClose(HDF4_EOS:EOS_SWATH:"/dprof_data/tmp/scenes/LE70210502019290EDC00/wvp/MYD05_L2.A2019290.1950.061.2019295131917.hdf":mod05:Water_Vapor_Near_Infrared, this=0x55a33c085330)
ERROR 4: : No such file or directory
ERROR 10: Pointer 'hDataset' is NULL in 'GDALGetRasterXSize'.

ERROR 10: Pointer 'hDataset' is NULL in 'GDALGetRasterYSize'.

ERROR 10: Pointer 'hDS' is NULL in 'GDALGetRasterBand'.

ERROR 10: Pointer 'hBand' is NULL in 'GDALRasterIO'.

could not read image. 100.0% of useful frames.
free(): invalid pointer
Aborted (core dumped)
```

Unfortunately I'm not an experienced C programmer, so the details about why this could happen are mysterious to me, as is how to debug this further...

**Comment by davidfrantz** [comment]
Hmm... not sure what is going on there.

It seems that the opening of the hdf is ok. The opening of the subdataset seems to have worked, too.
But it does not really make sense that the subdataset is closed immediately. 

In line 720/721 in ``modwvp-ll.c`` we have these lines:

      subDS = GDALOpen(sdsname, GA_ReadOnly);
      nx = GDALGetRasterXSize(subDS); 

I am puzzled why GDAL closes the file again at this point.. Probably the mechanic of opening subdatasets has changed.. I am afraid this will need some research as I do not have an answer right away..

Cheers,
David

**Comment by vincentschut** [comment]
Yes, it puzzled me too. If there's anything I can do to research this further, please let me know.

**Comment by davidfrantz** [comment]
Thanks for the offer! You could probably have a look if you spot a clue in the gdal changelog? 
Much appreciated, David

**Comment by vincentschut** [comment]
Ha, I already did that before I filed this issue, and found nothing that seemed related to this. Could have overlooked something, though, will scan again.

**Comment by vincentschut** [comment]
Only thing that seems very slightly related is this:

```
HDF4 driver:
 * do not report SDS when there are EOS_SWATH or EOS_GRID in it. Add LIST_SDS open option
```

(See also the small paragraph on LIST_SDS in the HDF4 format page: https://gdal.org/drivers/raster/hdf4.html#open-options)

However, I don't think it is that, as it seems force finds the right SDS without problems.

**Comment by vincentschut** [comment]
OK, I found it. And it *is* related to the change mentioned above.
In modwvp-ll.c:744-749, it is requesting "SUBDATASET_12_NAME" item from sds (because plat = 12). Due to the change in gdal, apparently the lat and lon subdatasets are not listed anymore, so SUBDATASET_12_NAME does not exist anymore.

I'm making a PR with a fix now (by setting LIST_SDS on opening the hdf). Please review carefully, as I'm totally not used to program in C, so I might miss some subtleties.
