### ISSUE TITLE
force-level2 blank BOA output for Landsat

### ISSUE THREAD

**Issue by fegyi001** [davidfrantz/force#6]
I have an issue regarding the Level-2 generation of Landsat imagery on the Dockerized version of FORCE v3.0.1. Maybe it only happens on my FORCE, but it worths a check. This is an issue I experienced also with FORCE v2.x and only with Landsat, not with Sentinel images.

The issue:
A force-level2 runs without errors, the logfile says _"...: dc:  62.22%. wc:   1.85%. sc:   0.17%. cc:  25.26%. AOD: 0.0000. # of targets: 346/2037. 56 product(s) written. Success! Processing time: 03 mins 08 secs..."_, and the level2 tile folders are created with the required raster images (BOA, QAI). The problem is that all BOA files are blank, meaning they contain 0 values at each pixel. What makes it even stranger that the QAI files are not blank at all, they contain the desired flags just as with Sentinel-2 images.

I also tried with a debug version of FORCE using `force-l2ps` for detailed output but the level2 results are the same. I saved the detailed output in a file: [out.txt](https://github.com/davidfrantz/force/files/4342591/out.txt).

This is how I called `force-l2ps` from the LC81880272018121LGN00 folder:
`force-l2ps imagery/ parameters.prm`

Here are my results with the detailed output:
https://my.pcloud.com/publink/show?code=kZNIs9kZHjoRv6qF9m0Miavl3i6AA7HAgbGy

What did I do wrong? As I said, with Sentinel-2 I got good results.

This is how my BOA files look like:
![image](https://user-images.githubusercontent.com/4125222/76841830-9de9ef00-6839-11ea-8c4f-72e8d14cb7ab.png)

Here are the QAI images:
![image](https://user-images.githubusercontent.com/4125222/76841975-d5589b80-6839-11ea-842a-c20f1c30d285.png)

**Comment by davidfrantz** [comment]
Hi Gergely, 

thanks for opening this issue. It's a quite unexpected result. I was able to reproduce the problem and was able to track it down to the DEM.

My log looks like this, note the difference in AOD:
/home/frantzda/temp/fegyi001/LC81880272018121LGN00/LC81880272018121LGN00: dc:  63.27%. wc:   1.80%. sc:   0.17%. cc:  25.01%. AOD: 0.1192. # of targets: 326/2022.  1 product(s) written. Success! Processing time: 01 mins 02 secs

With my own DEM:
![image](https://user-images.githubusercontent.com/32633788/76861067-4a3ccd00-685c-11ea-81ee-ef8e73c4219b.png)

There are 2 problems: the DEM does not cover the complete image (see below) and the nodata value in the parameterfile doesn't match the one in the image, -32767 and 0. Please also note that 0 is a bad choice for nodata in a DEM. However, I am still puzzled why any of those problems result in the zero reflectance... I will keep this issue open until I know what happens. 

In the meantime, I suggest to prepare a DEM that covers the complete image, and have a look at the nodata value. Please also see this tutorial: davidfrantz.github.io/tutorials/force-dem/dem/

![image](https://user-images.githubusercontent.com/32633788/76861234-8c660e80-685c-11ea-9339-16157892245a.png)

Best,
David

**Comment by fegyi001** [comment]
Thanks David for the prompt answer! This sounds promising, I'll give it a try right now.

**Comment by fegyi001** [comment]
Hello David,

The problem was indeed caused by the DEM.
With a new, proper elevation model the results are as expected:

![image](https://user-images.githubusercontent.com/4125222/76945063-4fecee00-6902-11ea-9c21-44c8ac0e5dda.png)

Thanks for the help!
It's up to you now to close the issue, on my behalf it is closed :)
