### ISSUE TITLE
[Enhancement] Level2 DEM_NODATA

### ISSUE THREAD

**Issue by jakimowb** [davidfrantz/force#7]
It is a bit unclear how the level2 processing handles the DEM_NODATA value or if it hast to be defined at all. Is it necessary to define it in the level2 paramter file, even if it is already given in the FILE_DEM image's metadata?

````
# Nodata value of the DEM.
# Type: Integer. Valid range: [-32767,32767]
DEM_NODATA = -32767
````

An enhancement could be like this:

````
# Nodata value of the DEM (optional)
# Type: Integer. Valid range: [-32767,32767]
# Set to NULL to use the nodata value defined in the image metadata.
DEM_NODATA = NULL
````

**Comment by davidfrantz** [comment]
Hi Benjamin,

it has to be given in the parameter file. 

Thanks for your suggestion, I already tried something like this before, but it didn't work.

There is an issue with GDAL, at least in the version I am using and which is the standard Ubuntu 18.04 version. 

GDAL doesn't read the nodata correctly, it always returns 0. 
However, it reads it correctly if I put a "#define DEBUG" preprocessor option in the code. This apparently triggers something in GDAL, but processing satellite data with a GDAL in DEBUG mode is not really a good idea. It may well be that this is already solved in GDAL, but for now, it needs to stay this way in FORCE.

Best,
David
