### ISSUE TITLE
force-level2: Snow cover exceeding threshold of MAX_CLOUD_COVER_FRAME = 0 product(s) written

### ISSUE THREAD

**Issue by maawoo** [davidfrantz/force#72]
**Describe the bug**
In short:
If the snow cover of a scene exceeds the threshold given via MAX_CLOUD_COVER_FRAME, no products will be written even though processing still happens. 

More information/background:
I stumbled upon this bug purely by chance, because I happened to check the level-2 output of a very snowy scene and noticed that it was not what I expected. In the following you can see the level-1 scenes that cover my AOI (the state of Thuringia). You can see some wispy clouds in the lower left, but other than that it's snow.  

![Screenshot from 2021-04-01 11-09-18](https://user-images.githubusercontent.com/56583917/113289737-279f1a00-92e0-11eb-940a-0f3e93463785.png)

Here is the level-2 output. The blue grid is the GLANCE7 grid that I used for processing. I'm also using a DEM in the shape of my AOI, which afaik shouldn't cause any (unrelated) problems... right? 

![Screenshot from 2021-04-01 11-09-35](https://user-images.githubusercontent.com/56583917/113290287-f4a95600-92e0-11eb-9f3f-84a3058811a6.png)

In my parameter file I used **75** as a threshold for both MAX_CLOUD_COVER_FRAME and MAX_CLOUD_COVER_TILE. 
Here is the log output where you can see that cloud cover is always well below threshold, but curiously the only scenes that produced an output are the ones with a snow cover below the given threshold! 🕵🏻 🔎 

```
/level1/sentinel2/T32UNA/S2A_MSIL1C_20170127T102301_N0204_R065_T32UNA_20170127T102258.SAFE: dc:   2.54%. wc:   0.11%. sc:  85.01%. cc:  21.30%. AOD: 0.2516. # of targets: 110/187.  0 product(s) written. Success! Processing time: 13 mins 31 secs
/level1/sentinel2/T32UNB/S2A_MSIL1C_20170127T102301_N0204_R065_T32UNB_20170127T102258.SAFE: dc:  32.64%. wc:   0.21%. sc:  77.08%. cc:  14.03%. AOD: 0.2225. # of targets: 654/2880.  0 product(s) written. Success! Processing time: 20 mins 02 secs
/level1/sentinel2/T32UNC/S2A_MSIL1C_20170127T102301_N0204_R065_T32UNC_20170127T102258.SAFE: dc:   8.05%. wc:   0.15%. sc:  85.21%. cc:  12.53%. AOD: 0.2424. # of targets: 93/303.  0 product(s) written. Success! Processing time: 10 mins 14 secs
/level1/sentinel2/T32UPA/S2A_MSIL1C_20170127T102301_N0204_R065_T32UPA_20170127T102258.SAFE: dc:  16.51%. wc:   0.61%. sc:  80.58%. cc:  11.57%. AOD: 0.1977. # of targets: 1478/2600.  0 product(s) written. Success! Processing time: 18 mins 38 secs
/level1/sentinel2/T32UPB/S2A_MSIL1C_20170127T102301_N0204_R065_T32UPB_20170127T102258.SAFE: dc:  85.96%. wc:   0.47%. sc:  66.74%. cc:  12.40%. AOD: 0.2098. # of targets: 3571/7550.  2 product(s) written. Success! Processing time: 34 mins 17 secs
/level1/sentinel2/T32UPC/S2A_MSIL1C_20170127T102301_N0204_R065_T32UPC_20170127T102258.SAFE: dc:  10.40%. wc:   0.43%. sc:  63.78%. cc:  16.04%. AOD: 0.2358. # of targets: 208/492.  1 product(s) written. Success! Processing time: 15 mins 35 secs
/level1/sentinel2/T32UQA/S2A_MSIL1C_20170127T102301_N0204_R065_T32UQA_20170127T102258.SAFE: dc:   0.88%. wc:   0.68%. sc:  91.33%. cc:   2.01%. AOD: 0.1588. # of targets: 168/196.  0 product(s) written. Success! Processing time: 12 mins 38 secs
/level1/sentinel2/T32UQB/S2A_MSIL1C_20170127T102301_N0204_R065_T32UQB_20170127T102258.SAFE: dc:  17.07%. wc:   0.39%. sc:  91.47%. cc:  15.61%. AOD: 0.2171. # of targets: 1082/1377.  0 product(s) written. Success! Processing time: 16 mins 25 secs
/level1/sentinel2/T33UUS/S2A_MSIL1C_20170127T102301_N0204_R065_T33UUS_20170127T102258.SAFE: dc:   7.09%. wc:   0.33%. sc:  94.56%. cc:  27.64%. AOD: 0.2657. # of targets: 118/189.  0 product(s) written. Success! Processing time: 13 mins 28 secs
```

I processed the same scenes with the same setup and parameter settings, except changing MAX_CLOUD_COVER_FRAME and MAX_CLOUD_COVER_TILE to **100**. Lo and behold, all scenes produced an output 🎉 

```
/level1/sentinel2/T32UNA/S2A_MSIL1C_20170127T102301_N0204_R065_T32UNA_20170127T102258.SAFE: dc:   2.54%. wc:   0.11%. sc:  85.01%. cc:  21.30%. AOD: 0.2516. # of targets: 110/187.  1 product(s) written. Success! Processing time: 14 mins 17 secs
/level1/sentinel2/T32UNB/S2A_MSIL1C_20170127T102301_N0204_R065_T32UNB_20170127T102258.SAFE: dc:  32.64%. wc:   0.21%. sc:  77.08%. cc:  14.03%. AOD: 0.2225. # of targets: 654/2880.  3 product(s) written. Success! Processing time: 22 mins 00 secs
/level1/sentinel2/T32UNC/S2A_MSIL1C_20170127T102301_N0204_R065_T32UNC_20170127T102258.SAFE: dc:   8.05%. wc:   0.15%. sc:  85.21%. cc:  12.53%. AOD: 0.2424. # of targets: 93/303.  1 product(s) written. Success! Processing time: 10 mins 21 secs
/level1/sentinel2/T32UPA/S2A_MSIL1C_20170127T102301_N0204_R065_T32UPA_20170127T102258.SAFE: dc:  16.51%. wc:   0.61%. sc:  80.58%. cc:  11.57%. AOD: 0.1977. # of targets: 1478/2600.  1 product(s) written. Success! Processing time: 20 mins 03 secs
/level1/sentinel2/T32UPB/S2A_MSIL1C_20170127T102301_N0204_R065_T32UPB_20170127T102258.SAFE: dc:  85.96%. wc:   0.47%. sc:  66.74%. cc:  12.40%. AOD: 0.2098. # of targets: 3571/7550.  2 product(s) written. Success! Processing time: 34 mins 06 secs
/level1/sentinel2/T32UPC/S2A_MSIL1C_20170127T102301_N0204_R065_T32UPC_20170127T102258.SAFE: dc:  10.40%. wc:   0.43%. sc:  63.78%. cc:  16.04%. AOD: 0.2358. # of targets: 208/492.  1 product(s) written. Success! Processing time: 15 mins 50 secs
/level1/sentinel2/T32UQA/S2A_MSIL1C_20170127T102301_N0204_R065_T32UQA_20170127T102258.SAFE: dc:   0.88%. wc:   0.68%. sc:  91.33%. cc:   2.01%. AOD: 0.1588. # of targets: 168/196.  1 product(s) written. Success! Processing time: 13 mins 12 secs
/level1/sentinel2/T32UQB/S2A_MSIL1C_20170127T102301_N0204_R065_T32UQB_20170127T102258.SAFE: dc:  17.07%. wc:   0.39%. sc:  91.47%. cc:  15.61%. AOD: 0.2171. # of targets: 1082/1377.  2 product(s) written. Success! Processing time: 18 mins 13 secs
/level1/sentinel2/T33UUS/S2A_MSIL1C_20170127T102301_N0204_R065_T33UUS_20170127T102258.SAFE: dc:   7.09%. wc:   0.33%. sc:  94.56%. cc:  27.64%. AOD: 0.2657. # of targets: 118/189.  1 product(s) written. Success! Processing time: 13 mins 11 secs
``` 
![Screenshot from 2021-04-01 14-57-06](https://user-images.githubusercontent.com/56583917/113297290-f4fa1f00-92e9-11eb-8563-08cbb0a6bac9.png)

**Parameterization**
[FORCE_params__20210331T105111.txt](https://github.com/davidfrantz/force/files/6243362/FORCE_params__20210331T105111.txt)

**Setup**
- FORCE version
I'm using v3.6.5 in a [Singularity](https://sylabs.io/guides/3.7/user-guide/introduction.html) container, which was converted from the official Docker version. 
I'd be very surprised if this caused the problem. But just to be sure, maybe someone else can verify with another installation that this problem exists? 

- RAM and number of CPUs on your machine
HPC with enough RAM and CPU

----

Happy Easter holidays!

**Comment by davidfrantz** [comment]
Hi Marco,

hmm, yes you are right.

For ``MAX_CLOUD_COVER_FRAME``, I am considering cloud and cloud shadow. 

For ``MAX_CLOUD_COVER_TILE``, I am obviously considering cloud, cloud shadow, and snow... 

Sorry for this oversight. I guess it would make sense to remove the snow from this test. 

I will prepare a bugfix after the Easter break. 

Happy egg hunting!
David

**Comment by maawoo** [comment]
Great, thanks! 
I actually started out with another problem where the process for this scene didn't finish at all (in the end it was just the parallel read parameter). So at some point I wasn't sure anymore if it's just coincidence or if something else is horribly wrong on my end. I'm just glad it's not the latter 🙂 

Cheers, Marco

**Comment by davidfrantz** [comment]
Hi Marco,

the snow issue is now fixed with https://github.com/davidfrantz/force/commit/ed8d318d8f45470613d42a1977170cfdbf8c2393 in the develop branch. I guess that I will publish a new main release soon as some interesting new features were finalized recently. 

Thanks again for bringing this forward!

Cheers,
David
