### ISSUE TITLE
Statistical metrics (STMs) incorrectly calculated for interpolated time-series that includes repetition

### ISSUE THREAD

**Issue by leonsnill** [davidfrantz/force#73]
**Potential Bug**
I have observed some pixels to exhibit incorrect statistics (STMs, e.g. Q10) when comparing the FORCE calculated values to "manually" calculated statistics by looking at the RBF interpolated TSI values. So far, I could only find such a behaviour when the TSI has repetitive values.

**Example**
RBF based TSI of MNDWI values (zeros are actually NaNs and only displayed as zeros):

![image](https://user-images.githubusercontent.com/53185790/113877669-35a9da80-97b9-11eb-943b-189efabd900f.png)

The associated STM values:

![image (1)](https://user-images.githubusercontent.com/53185790/113877671-36427100-97b9-11eb-8002-5737f3634fb9.png)

**Comment by davidfrantz** [comment]
This is somehow related to the quick-sort algorithm used to compute the quantiles. 
There seems to be some hiccup when repetitive values are included. I could not get to the bottom of it, though...

**Comment by davidfrantz** [comment]
This is now eventually fixed with f32cc673233e25ce417e84dd1a0d61ce3830d8cd
