### ISSUE TITLE
Conflict in outlier removal (QAI SCREENING) when using dense time series (>= 3 obs. / day)

### ISSUE THREAD

**Issue by leonsnill** [davidfrantz/force#74]
**Problem**
Using the ``ABOVE_NOISE`` and ``BELOW_NOISE`` parameters (section QAI SCREENING) for TSA processing together with dense time series may cause a floating point exception. This happens if for any individual pixel there are >= 3 observations for a single date, which may only apply if multi-annual time series are (artificially) densified into a single year.

Not using the filtering, i.e. setting both parameters to zero is a temporary solution to the problem.

**Comment by davidfrantz** [comment]
With [fix triple obs 0 division](https://github.com/davidfrantz/force/commit/906c4b1886b3c588167c7cb8df852c4e78d910ba), this should be fine now :)
