### ISSUE TITLE
Argument -n in force-level1-csd not working properly

### ISSUE THREAD

**Issue by davidfrantz** [davidfrantz/force#80]
Issue as discussed by @corneliussenf and others in https://github.com/davidfrantz/force/discussions/77_

The option ``-n`` in ``force-level1-csd`` does not work as expected when used as 1st argument.

As @ernstste suggested, there are currently two ways to work around this:

- do not use -n as first argument, but after other arguments
- use the long option --no-act instead

Unfortunately, we do not have any clue why this happens. 
**Help wanted!**
We are using the ``getopt`` utility for this, see https://github.com/davidfrantz/force/blob/develop/bash/force-level1-csd.sh

Best,
David

**Comment by ernstste** [comment]
Fixed in commit [38a04e6](https://github.com/davidfrantz/force/commit/38a04e6fb2b61469f6e1bd9b04a58ab203d1289c )
